default_categories = {
    "Website Content / App Critical Feedback": {
        "Help Pages and FAQs are hard to find": ["I can't find the help pages", "Do you even have a help center?", "Where are the FAQs?"],
        "Missing Product Details": ["The product details are missing on the website", "Where are the product specs for this cell phone?", "I can't find information about the product on the website"],
        "Promotion Details Not Clear or Hard to find": ["The promotion details are unclear", "How do I find the current offers", "Offers and discounts are hard to find on the website", "What are the terms and conditions of this deal on the site?", "How do I take advantage of this offer?", "I don't understand the promotion details on the website"],
        "Accessibility Options do not work": ["The accessibility options on the website are not working", "How do I access the disability options on Samsung.com?", "I'm having trouble with the website's accessibility options"],
        "Contact Us options are hard to find": ["I can't find the contact support options", "The phone number to reach you was disconnected", "Calling support was hard, simply because the number was no where to be found.", "How do I get ahold of you for support?", "Where can I find the 'Contact Us' options?"],
        "My Orders Page Feedback": ["I have feedback about the 'My Orders' page", "I'm not able to return my order on the my orders page", "I'm having issues with the 'My Orders' page"],
        "Pop Up - Feedback": ["I have feedback about the website pop-ups", "there are too many pop ups on the site.", "The website pop-ups are annoying"],
        "Search Feature - Poor Results": ["The website's search feature gives poor results", "I'm having trouble finding the right product on the website", "I can never find what I'm looking for when I search Samsung.com", "The search bar is worthless", "I'm not satisfied with the search results on the website"],
        "Product Compare Tool Feedback": ["I have feedback about the product comparison tool", "No clear way to compare multiple products on the website", "The product comparison tool on the website could be improved"],
        "Outlet or Live Commerce Pop Up": ["The outlet pop-up on the website is intrusive", "Who wants to watch people talk about a product", "Why are these annoying people talking about the new phone?", "I have feedback about the live commerce pop-up"],
        "Mobile Webpage and App Feedback": ["I'm having problems with the mobile webpage", "Buggy experiences on the Mobile browswer", "I can't get the page to load on my phone", "The Shop Samsung app is garbage", "The app is not working properly"],
        "Website Feedback - Search Functionality": ["I have feedback about the search functionality", "The search functionality could be improved"],
        "Website Feedback - Slow and Laggy": ["The website is slow and laggy", "Pages take forever to load", "The Site is soooo slow!", "All these pictures make it take forever to load a page", "I have fast internet, but your website is always so slow", "I'm experiencing performance issues with the website"],
        "M Web & App Feedback - Slow and Laggy": ["The mobile app is slow and laggy", "Fix the app", "It takes forever to load up a page when using my phone to search Samsung.com", "I'm experiencing performance issues with the mobile app"],
        "EPP Store - Unable to Navigate Away": ["I'm stuck in the employee store and can't navigate away", "How Can I get out of the employee store?", "I can't get out of the employee store on the website"],
        "Navigation Issues for Samsung Business Store": ["I'm having navigation issues with the Samsung Business Store", "How do I get out of Samsung Business?", "The Samsung Business Store is hard to navigate"],
        "Website Feedback - Crashing": ["The website keeps crashing, making it hard to browse and order", "The site has been down for a long time", "I'm having trouble ordering because the website keeps crashing"],
        "Website Feedback - Design": ["The banners on the page block information and make it more difficult than it needs to be to find details", "Apple still has a better website, you should copy them", "The Samsung Programs drop down is so annoying", "I have to minimize the programs thing every time I open a link", "The website is not User Friendly at all"],
        "Website Feedback - 404 Errors": ["I've never seen so many 404 errors", "Everything I click on results in a 404 error.", "Pages were not loading", "404"],
        "Website Feedback - Buggy or Poor performance": ["This is the buggiest website I have ever used", "Samsung.com is glitchy", "Please fix the website", "Everytime I browse the website, I find a new issue with it", "Why is the website set up this way? It is always mishaving"],
        "Website Feedback - Inaccurate Geolocation": ["The website did not use my geo-location accurately", "The website thinks I'm in another country", "Samsung thinnks I'm not in the US, but I am", "The website is not accurately detecting my location"]
    },
    "Product Support, Warranty and Repair (Care)": {
        "Loaner Phone Request for repair": ["I need a loaner phone for the repair", "Can I get another phone temporarily while mine is out for repair?", "What am I supposed to do without a working phone?", "Can I get a loaner phone while my phone is being repaired?"],
        "Product Registration issues - unable to register": ["I'm having issues registering my Samsung product", "How do I register a device to my account?", "I can't register my Samsung product"],
        "Cost of Repair is too high": ["The cost of repair is too high", "it's way too expensive to repair my samsung product.", "I can't afford the repair cost"],
        "Multiple Repair Requests": ["I have to make multiple repair requests", "I've had to repair my product far too many times at this point.", "Why do I need to request a repair multiple times?"],
        "Outside of Warranty Coverage - Unable to have device fixed": ["My device is outside of warranty coverage and can't be fixed", "What do you mean I'm outside warranty?!", "I can't get my device fixed because it's out of warranty"],
        "Repair Lost in Transit": ["My repair got lost in transit", "Where's my original phone? The carrier lost it?", "What do I do if the shipper lost my repaired phone?", "The courier lost my device that was sent for repair"],
        "Care Plus + Subscription Coverage": ["I have a question about Care Plus+ subscription coverage", "What all is covered by Care", "Why should I get Care Plus?", "What are the advantages of the Care Plus Program?", "Can you tell me more about Care Plus+ subscription coverage?"],
        "Need Help Troubleshooting Product": ["I need help troubleshooting my product", "Are there any troubleshooting steps you can recommend to fix this?", "Can you help me troubleshoot my product?"],
        "Troubleshooting steps did not work": ["The troubleshooting steps did not work", "I followed all the steps to fix it, but the issue persists", "Troubleshooting didn't help at all.", "I tried troubleshooting but it didn't help"],
        "Product Issues Were not Resolved by Care": ["Care did not resolve my product issues", "I have reached out to product support again and again, no luck", "I haven't had any luck with Care", "My product issues were not resolved by Care"],
        "Technical Product Support Did not Follow Up": ["Technical product support did not follow up", "I didn't get a follow-up from technical product support"],
        "Received Incorrect Troubleshooting": ["I received incorrect troubleshooting from product tech support", "The troubleshooting advice from tech support was wrong"],
        "Technical Product Support Hours Were Limited": ["The technical product support hours are too limited", "I need tech support but the hours are too limited"],
        "Repair Work Was Unsatisfactory": ["The repair work was unsatisfactory", "You call this repaired?", "My device was not actually repaired.", "It's like they didn't even work on this.", "I'm not satisfied with the repair work"],
        "Repair Work Took Too Long": ["The repair work took too long", "It was over a month to get my phone back from being repaired", "I had to wait too long for the repair"]
    },
    "Return and Refund Issues": {
        "Return Refund Processing Time": ["The return refund processing time is too long after the return was delivered", "Y'all have had my return for weeks now, where's my refund?", "How long does it take to process a Return?", "It's been more than 10 days since my return was delivered to you. Where is my refund?", "How much longer do I have to wait for a refund on my return?", "How long does it take to process a refund after the return is delivered?"],
        "Return Window Extension Request to ship return later": ["I need an extension on the return window to ship the return later", "I need more time to send in my Return", "I didn't realize how much time has passed", "I only opened this recently and now want to return it", "Can I get an extension on the return window?"],
        "Return Shipping Label Request": ["I need a return shipping label, I've already requested a return", "can you help me with the return mailing label?", "Can I get a return shipping label?"],
        "Return to Reorder Feedback": ["I'm frustrated that I have to wait for a return and refund before I can place a new order", "Can you just give me my money back so I can place a new order already?", "Why do I have to wait for a return and refund to place a new order?"],
        "Shipping Label Print Requirement, need to print label": ["I need to print the shipping label for the return", "can I drop this off somewhere to return it?", "I don't have a printer to print the return label", "What do I do without a printer?", "Can you send me a printable shipping label for the return?"],
        "General Return Policy - How to Return, restrictions?": ["Can you explain the return policy and how to return an item?", "how do I return an order from Samsung.com?", "Can I return this?", "What are the restrictions on returns?"],
        "Wrong Return Refund Amount received after Return": ["I received the wrong refund amount after returning an item", "The refund amount I received after the return is incorrect"],
        "Return Failed - No Refund": ["My return failed and I didn't receive a refund", "I didn't get a refund because my return failed"],
        "Return failed - Unsent": ["My return failed and it was unsent", "I received an e-mail claiming that I returned an empty box", "I received an e-mail from Samsung that my return was Unsent", "The return was not sent because it failed"],
        "Installation Charge Not Refunded": ["My installation charge was deducted from the return refund", "I want a refund for my installation", "I shouldn't have to pay for the installation on a product I returned", "Why was the installation charge deducted from my refund?"],
        "Return Not Available": ["I had difficulty initiating a return, there's no return option available", "Why can't I return this?", "I can't initiate a return because there's no return option"],
        "I want a Refund for an order I placed": ["I want a refund for an order I placed", "Can I get a refund for my order?"],
        "I want an Exchange or Replacement": ["I want to exchange or replace my product", "Can I send this back for a different one?", "Can I get a replacement or exchange my product?"],
        "Refund Was Not Issued After Return": ["I didn't receive a refund after returning the product", "The refund was not issued after I returned the product"],
        "Restocking Fees Deducted From Refund": ["Restocking fees were deducted from my refund", "Why were restocking fees deducted from my refund?"],
        "Return Pick Up Needed": ["I need the order to be picked up for return, I can't ship it", "Will someone come pick this up for me?", "Can you arrange a pick-up for my return? I can't ship it"],
        "Received Partial Refund": ["There are discrepancies in the partial refunds", "I have a question about the partial refunds", "I didn't get a full refund for my return", "My return was only partially credited"],
        "Tracking shipped Returned Item": ["I had difficulty tracking the returned item", "I can't track the item I returned"],
        "International Return": ["I had difficulties with an international return", "How do I return this if I left the US?", "Can I return this from abroad?", "International returns are difficult"],
        "Product Was Damaged During Return Shipping": ["The product was damaged during return shipping", "My returned product got damaged during shipping"],
        "Tax Exception - Tax Refund Needed": ["I need a tax refund due to a tax exception", "I'm tax excempt, can I get my tax refunded?", "Can I get a tax refund due to a tax exception?"],
        "Had Problems with Return Label": ["I had problems with the return label", "I get an error when trying to download the return mailing label", "The return label is not working"]
    },
    "Product Feedback": {
        "Charger Not Included with my order": ["The charger was not included with my order", "Why did you all remove the charger from the new phones?", "Oh look, another company doing away with a charger in the box.", "My order didn't come with a charger"],
        "Product Durability is poor": ["The product durability is poor", "This thing is flimsy", "I bet it will scratch really easily", "That looks like plastic", "I'm not satisfied with the product's durability"],
        "General Product Feedback": ["I have some general feedback about the product", "Here's my feedback about the product"],
        "Mobile Applications Feedback": ["I have feedback about the mobile applications", "Your Mobile app sucks", "Here's my feedback about the mobile apps"],
        "Feedback on Pre-Installed Apps": ["I have feedback about the pre-installed apps", "Can we do away with this bloatware?", "Here's my feedback about the pre-installed apps"],
        "Headphone / speaker port Feedback.": ["There's still no headphone or speaker port on the newest phones", "Another model without a headphone jack", "Why don't the newest phones have a headphone or speaker port?"],
        "Product Availability.": ["The product I wanted was out of stock when I tried to order it", "When will this be back in stock on the website?", "I couldn't order the product I wanted because it was out of stock"],
        "Product Missing Piece or Part": ["The product is missing a piece or part", "There's a piece or part missing from the product"]
    },
    "Policy Feedback": {
        "Inability to Replace Items": ["I'm frustrated at the inability to replace items", "Why can't I replace items?"],
        "Device Knox Locking and Disabling Policies": ["I have concerns about the device Knox locking and disabling policies", "Can you explain the device Knox locking and disabling policies?"],
        "Shipping Policy Critiques": ["I have some critiques about the shipping policy", "Here's my feedback about the shipping policy"],
        "Return Policy Critique": ["I have some critiques about the return policy", "Your return policy sucks", "The return policy on Samsung.com is pretty great", "Here's my feedback about the return policy"],
        "Accepted Payment Methods?": ["What are the accepted payment methods?", "What are the different payment methods?", "Can you tell me the accepted payment methods?"],
        "Tax Exception Policy": ["I have some general questions about the tax exception policy", "Can you explain the tax exception policy?"]
    },
    "Trade-In Related": {
        "Trade-In Charge - Unknown Reason": ["I don't like the trade-in chargeback process", "The trade-in chargeback process is not satisfactory", "Why was I charged for my trade-in?", "I am being charged for my Trade in"],
        "Trade-In Charge - Not Shipped": ["I sent in my Trade-in, but I'm still being charged and told that I did not ship it.","Received a message from Samsung that I didn't send in my trade in.", "Why am I being charged, I already sent my old phone", "Why was I charged for my trade-in, I just mailed it the other day?", "I am being charged for my Trade in for not sending it in, but I did already."],
        "Trade-In Charge - Empty Box": ["I sent in my Trade-in, but I'm being charged because y'all received an empty box.", "Received a message from Samsung that I sent an empty box for my trade in.", "I didn't send an empty box for my trade in.", "Why was I charged for my trade-in, my old device was in the box and it wasn't empty", "I am being charged for my Trade in because of an empty box, but I did not send an empty box. It must have been removed in transit."],
        "Trade-In Charge - Watch": ["I was charged for my Watch Trade in", "My Watch Trade in wasn't successful and I received a bill for it", "I was sent an e-mail from Samsung that I didn't send my Watch for trade in.", "I sent my Watch in for trade-in, but was still charged"],
        "Trade-In Charge - Cracked Screen": ["My phone wasn't cracked when I sent my trade in, why didn't I get full credit?", "I received a message from Samsung that my screen was cracked on my trade in device", "My old phone has a cracked screen, can I still trade it in for a discount?", "How much is this worth with a cracked screen, will I still get a discount?", "Cracked screen was marked, why didn't my trade-in go through all the way?", "It's saying my trade in was cracked. I disagree."],
        "Trade-in Program - Positive Feedback": ["I only shop on Samsung.com because of the trade in values", "Your trade in credit is unmatched", "Trading in my old devices is such a cool concept"],
        "Trade-In Program - Value Questions": ["How much is my phone worth as a trade in?", "What I can get by trading in my watch?", "Is it worth it to trade in my tablet?"],
        "Trade-In Program - Eligibility and Process": ["The trade-in details are confusing", "How do I do the trade in thing?", "Does my device qualify for your trade in program?", "I don't understand the trade-in details when adding a trade-in"],
        "Trade-In Discount Changed in Cart": ["My trade in credit is changing once I get into the cart or checkout", "The full value of my trade in isn't being reflected in checkout."]
    },
    "Cancelled Orders - System Cancellation": {
        "Order cancelled by System": ["My order was cancelled - I chose the financing option", "My order was cancelled several times, even though I tried to order again and again", "Why was my order cancelled multiple times? I kept trying to order", "My order was cancelled for an unknown reason", "My Watch order was cancelled", "My phone order was cancelled", "My Tablet order was cancelled", "My Home Appliance order was cancelled", "Why was my order cancelled? I don't understand the reason", "My order was cancelled - I chose the buy online pickup in store option", "The order I placed for Best Buy was cancelled", "My order was cancelled for an unknown reason", "My Watch order was cancelled", "My phone order was cancelled", "My Tablet order was cancelled", "My Home Appliance order was cancelled", "Why was my order cancelled? I don't understand the reason", "Why was my order cancelled? I chose to pick it up in store", "My order was cancelled due to fraud", "I received an e-mail from Samsung saying my order was cancelled because some or all of my payment information could not be verified.", "Why was my order cancelled for fraud?", "Order cancelled repeatedly, regardless of payment method", "Payment method charged despite order being cancelled", "Order cancelled shortly after multiple attempts to place it", "Repeated order cancellation notifications from Samsung", "I ordered with Samsung financing, by my order is getting cancelled", "Why was my order cancelled? I chose to finance it"],
        "Order cancelled - Outside the US": ["My order was cancelled because my payment method is from outside the US United States","My order was cancelled because my payment method is from Mexico","My order was cancelled because my payment method is from Russia","My order was cancelled because my payment method is from Canada", "Is my order cancelled because I'm from outside the U.S.?"],
    },
    "Post-Checkout Order Modification and Management": {
        "Unable to Change Available Delivery Options": ["I'm unable to change the available delivery options", "Can I change my shipping method to get this faster?", "I can't change the delivery options for my order"],
        "Unable to Cancel order": ["I'm unable to cancel my order", "why Can't I cancel my order?", "My order hasn't even shipped yet, why can't I cancel it?", "I can't cancel my order"],
        "Unable to Modify Products on order": ["I'm unable to modify the products on my order", "I can't change the products on my order"],
        "Unable to Add Product to Order": ["I'm unable to add a product to my order", "Can I add another product to my order?", "I can't add a product to my order"],
        "Unable to Modify Payment Methods": ["I'm unable to modify the payment methods for my order", "I need to change my credit card", "Can I switch the payment method?", "I can't change the payment methods for my order"],
        "Customer Cancel - Modify Order": ["I had to cancel my order to make changes, like choosing a different color", "Why do I have to cancel my order to make changes?"],
        "Customer Cancel - Unknown Reason": ["I want to cancel an order I placed", "cancel my order please", "I no longer want my order", "Can I cancel my order?"]
    },
    "Shipping and Delivery": {
        "Where is my Order - Order has not shipped yet - Late": ["Where is my order? It hasn't shipped yet and it's late", "My order was supposed to be here already and it hasn't even shipped yet", "My order is late and it hasn't shipped yet"],
        "Check Status of Order": ["When will my order ship and be delivered?", "Is everything okay with the order I placed?", "Can you tell me when my order will ship and be delivered?"],
        "Where is my Order - Order has shipped - Late": ["Where is my order? It has shipped but it's late", "The carrier has my order, where is it?", "Fedex has my order, where is it", "UPS has my shipment, what's happening with it now?", "It's been with RXO for too long already, where is my order?", "My order is late even though it has shipped"],
        "Where is my Order - Order Lost in Transit, no Tracking Updates": ["Where is my order? It's lost in transit and there are no tracking updates", "There haven't been any tracking updates at all!", "My order is lost in transit and I can't track it"],
        "Where is my Order - Delivery Date Keeps Changing and Getting Pushed Out": ["Where is my order? The delivery date keeps changing and getting pushed out", "I keep getting notified by Samsung that my order isn't shipping and the delivery date keeps changing","The delivery date for my order keeps getting pushed out"],
        "Delivered, not Received": ["Make sure it's delivered if you say it's delivered", "Your carriers said it was delivered, but it's not here", "I received a notification stating my order was delivered", "Delivered my ass, it's not here", "Your website said this was delivered", "This was not delivered"],
        "Original Delivery Date Was Changed Immediately After Placing Order": ["The original delivery date was changed immediately after I placed the order", "The website showed one date, but then it pushed out a month right after I ordered it.", "It said it would get here in two days, but now it's going to take a week", "Why tell me it'll be here in a few days before I place the order, only to say it'll be another month after I order", "Your shipping dates feel like bait and switch, I just want what I ordered when you said you'd deliver it.", "Why was the delivery date changed right after I placed the order?"],
        "Where is my Order - Product Missing from Shipment": ["Where is my order? There's a product missing from the shipment", "This part of my order wasn't in the box I received", "A product is missing from my order's shipment"],
        "Wrong Product Received - Color": ["I received the wrong product - the color is incorrect", "I didn't order the color that was in the box", "The product I received is the wrong color"],
        "Wrong Product Received - Model": ["I received the wrong product - the model is incorrect", "The product I received is the wrong model"],
        "Wrong Product Received - General": ["I received the wrong product", "The product I received is not what I ordered"],
        "Product Delivered Damaged": ["My order was delivered damaged", "My fridge was delivered damaged", "The dishwaser was damaged, so I refused delivery", "I've had to reorder this several times because it keeps arriving cracked", "Get better delivery drivers, they keep breaking my order", "IT was smashed in the box", "This looks like it was ran over", "It has a giant hole in the package"],
        "BESPOKE Fridge / Refrigerator Panels - Not Shipped Delay": ["The BESPOKE fridge/refrigerator panels have not been shipped yet", "Where are my panels?", "Why haven't the BESPOKE fridge/refrigerator panels been shipped yet?"],
        "Customization and Exclusive Color delivery delay Time, weeks": ["The delivery of the customization and exclusive color is delayed by weeks", "Why is the delivery of the customization and exclusive color delayed?"],
        "Buy Online Pickup in store - Best Buy Pickup Delay": ["The pickup at Best Buy is delayed", "Why is the pickup at Best Buy delayed?"],
        "Buy Online Pickup in store - Best Buy Out of stock Delay": ["The pickup at Best Buy is delayed because the product is out of stock", "Why is the pickup at Best Buy delayed? The product is out of stock"],
        "Buy Online Pickup in store - Best Buy No Pick Up Ready Confirmation": ["I didn't receive a pick-up ready confirmation from Best Buy", "Why haven't I received a pick-up ready confirmation from Best Buy?"],
        "Where is my order - Order Delivered, but not Received": ["Where is my order? It was delivered but I didn't receive it", "My order was delivered but I didn't receive it"],
        "Defective Product delivered and Received, DOA, unit does not work": ["I received a defective product, it doesn't work", "The product I received is defective and doesn't work"],
        "No Tracking Information - UPS": ["I don't have any tracking information from UPS", "Why haven't I received any tracking information from UPS?"],
        "No Tracking Information - AGS": ["I don't have any tracking information from AGS", "Why haven't I received any tracking information from AGS?"],
        "No Tracking Information - Buy Online Pickup in store": ["I don't have any tracking information for my buy online pickup in store order", "Why haven't I received any tracking information for my buy online pickup in store order?"],
        "No Tracking Information - FedEx": ["I don't have any tracking information from FedEx", "Why haven't I received any tracking information from FedEx?"],
        "No Tracking Information - Forward Air": ["I don't have any tracking information from Forward Air", "Why haven't I received any tracking information from Forward Air?"],
        "No Tracking Information - RXO": ["I don't have any tracking information from RXO", "Why haven't I received any tracking information from RXO?"],
        "No Tracking Information - Unknown": ["I don't have any tracking information", "Why haven't I received any tracking information?"],
        "Received Damaged Product, scratched, dented, etc": ["I received a damaged product, it's scratched and dented", "The product I received is damaged, it has scratches and dents"],
        "Where is my Order - Delivery Date was Missed": ["Where is my order? The delivery date was missed", "The delivery date for my order was missed"],
        "Where is my Order - Inaccurate Delivery Tracking": ["Where is my order? The delivery tracking is inaccurate", "The delivery tracking for my order is inaccurate"],
        "Unable to checkout - Limited Delivery Zones, shipping restriction": ["I'm unable to checkout due to limited delivery zones and shipping restrictions", "I can't order because I'm outside the US", "Why can't I checkout? There are shipping restrictions and limited delivery zones"],
        "Where is my Order - Delivered to Wrong Location or Address": ["Where is my order? It was delivered to the wrong location or address", "My order was delivered to the wrong location or address"],
        "Where is my Order - Delivery Attempted, but not completed": ["Where is my order? The delivery was attempted but not completed", "The delivery for my order was attempted but not completed"]
    },
    "CS & ePro Contact Feedback": {
        "Customer Service Agent Unable to Solve Issue": ["The customer service representative couldn't resolve my issue", "I'm unsatisfied with the problem-solving ability of the customer service agent"],
        "Feedback - Time to Connect": ["Why was the waiting time to connect with customer service so long?", "I had to wait too long to reach customer service"],
        "Agent Knowledge is lacking": ["The customer service agent seemed uninformed", "Your agents should be trained better", "The representative didn't have enough knowledge to help me"],
        "agent Knowledge - Promotions": ["Your agents didn't even know the promo details", "Why Do I know more than your agents about the current offers?", "Give your agents more promotion training", "They didn't even know about the reserve credit", "THe reps should have more knowledge about the deals on your website", "Samsung.com has a whole deal page, why don't your agents even know that much?"],
        "Agent Ownership and follow": ["The customer service representative failed to follow up", "The customer service agent did not take responsibility for my issue"],
        "Technical Issues - Time to Resolve": ["It took too long to fix my technical issues", "The resolution of my technical problem was delayed"],
        "Contact Disconnected": ["My call was disconnected and I received no callback or email", "I'm disconnected everytime I call", "My chats are disconnecting", "I was disconnected and received no follow-up"],
        "Feedback - Long Hold": ["I had to wait a long time for a response from the agent", "I was kept on hold for too long during the call", "The hold time during the conversation was too long", "I was on hold for hours", "they put me on hold for several minutes", "The agent's response time was too long"],
        "Language Barrier with Customer Support Staff, Difficult to Understand": ["I had difficulty understanding the customer support due to a language barrier", "The customer service agent's accent made communication difficult"],
        "Too Much Time Between Chat Replies": ["The chat responses were too slow", "Each response took forever in chat", "It took too long to get responses in the chat"],
        "Lack of Empathy from Customer Support Staff": ["The customer service agent lacked empathy", "I didn't feel understood by the customer service representative"],
        "Supervisor was Not Helpful during call or chat": ["The supervisor on the call was not helpful", "Your Supes were not helpful either", "What's the point of connecting to leadership if they can't do anything either?", "I didn't find the chat supervisor helpful"],
        "Agent Would Not Escalate or Let Me Talk / chat with Supervisor": ["The agent refused to escalate my issue", "I wasn't allowed to speak with a supervisor"],
        "Customer Switching to Competitor": ["I'm considering switching to Apple due to poor service", "I will never by Samsung again", "I'm never buying Samsung again, Apple only", "Due to this bad experience, I'm thinking of going to a competitor like Apple"],
        "Customer service Agent is repeating the same troubleshooting or advice and it continues to not be effective.": ["The agent keeps repeating the same ineffective troubleshooting steps", "The agent's advice is not solving the issue, yet they keep repeating it"],
        "Customer service is closed, unable to call or chat, no one is available to help me.": ["I can't reach customer service, it's closed", "I can't call or chat with anyone, customer service seems to be closed"],
        "Supervisor or Leader is Required": ["I need to speak with a supervisor right now", "Have a member of leadership contact me", "Make a supervisor call me", "It's important for me to talk to a leader immediately"]
    },
    "Checkout and Cart Issues": {
        "Unable to checkout - Payment Issue": ["Unable to process payment during checkout", "Samsung Financing issues prevent checkout", "Carrier Financing problems stopping me from ordering", "Credit Card issue, unable to place order", "Apple Pay, PayPal not working", "Affirm Financing isn't working for payments", "Klarna Financing is not available for my purchase", "Unknown payment method type", "Available financing credit isn't working", "Using Paypal didn't work", "My credit card keeps getting declined, but I have an avaialble balance", "Payment processing issue"],
        "Long Delivery Time": ["Delivery time is too long", "Why is it going to take weeks for this product to be delivered?", "Expected delivery time deters purchase"],
        "Carrier Website Issues": ["Unable to log into Verizon's site to finish checkout", "Unable to log into T-Mobile's website for checkout", "Login issues on AT&T are preventing checkout"],
        "Price Issue": ["Price changes during checkout", "The cost of the product was less before I tried to order it, than it became much more expensive when I tried to order it.", "Discrepancy between product page price and cart price"],
        "Checkout Error Messages": ["Error message prevents checkout", "I tried to place an order over 5 times", "Have gone through checkout process several times and cannot complete an order", "I get an error message every time I try to make a purchase", "Unable to checkout due to error message"],
        "Finance Offer Changes": ["Finance offer changes during checkout", "it goes from 12 to 36 months for financing", "Alterations in finance offer in the cart and at checkout"],
        "Promotion EPP Issue - Discount": ["Employee Purchase Program discount issue", "Student or Teacher discount isn't working", "First Responder or Military discount problem"],
        "Promotion Issue": ["Promotion isn't being applied", "I have credit available, but I can't use it", "I have a samsung gift card, but it doesn't work", "Apply credit to an order is way too difficult", "Promo code has already been used on another order", "Invalid promo code"],
        "Reward Points Issue": ["Reward points not applied to my order", "My Rewards points are gone", "I can't apply the rewards to my order", "Unable to use reward points"],
        "Split Payment Issue": ["Split payment option isn't working", "Issues with multiple payment options"],
        "Unable to checkout": ["Unable to checkout due to technical issue", "Just have your website work when checking out", "I cannot place an order", "Technical problems prevent checkout"],
        "$50 Reserve Reservation Promo Credit Issue": ["$50 Reserve Reservation promo credit not applying", "I reserved, now where's my coupon?", "Invalid or unapplied $50 Reserve  promo credit"],
        "Shipping Issues": ["Limited shipping methods and speeds", "Unable to verify shipping address error message at checkout"],
        "Carrier Experience": ["Logging in and using my carrier account was so frustrating", "I had a terrible experience opening and using my ATT account", "Using Verizon on your site was very difficult", "Using my TMOBILE account was very hard"],
        "Cart Issue": ["All products removed from cart", "Everytime I add a new product to my cart, another product is removed", "I had to make several purchases because I couldn't have all the items in my cart at the same time.", "I am unable to add items to my cart to checkout", "it is difficult to buy multiple products at one time", "Unable to modify quantity of order"]
    },

    "Installation Problems": {
        "Delivered, Not Installed": ["The installation process is complex and requires multiple visits by the installers", "It took more than 7 days to instal the order after it was delivered", "My fridge was dropped off days ago and it still isn't installed", "How are you going to leave this here and not get it installed for me?"],
        "Missed Installation Appointment": ["The installers missed my installation appointment", "Installers didn't show up", "Where are the installers?"],
        "Late Arrival of Installers": ["The installers arrived late for the appointment", "Getting this installed has been such a pain, the drivers aren't even on time"],
        "Missing Installation Parts": ["There are missing parts, so I can't install the products", "THe installers were here, but didn't have the parts to finish installation", "I need a stacking kit to wrap up instal", "No steam kit included, so I can't have my dryer installed"],
        "Damages Caused by Installers": ["The installers damaged my home appliance", "My home or property was damaged during the installation", "The installers damaged my TV"],
        "Rude Installation Staff": ["The installation staff were rude during the service", "The istallers were assholes", "The installation staff treated me poorly"],
        "Post-Installation Product Issues": ["There are issues with the product after it was installed", "I had my TV mounted, but now there are lines on the screen", "My Home Appliances are making funny noises now"],
        "Installation Not Done At Delivery": ["The product was not installed at the time of delivery"]
    },
    "Privacy & Security Concerns": {
        "Website Data Security and Privacy": ["I have concerns about the security and privacy of my data on the website"],
        "Lack of Transparency in Data Usage": ["There's a lack of transparency in how my data is being used", "How is my data shared with others?", "Do you share my info with other parties?"],
        "Unknown Charges, Scams, & Phishing Experiences": ["I've experienced scams and phishing", "What is this charge for?", "What is this fee for?", "I didn't place this order and need it cancelled as soon as possible", "Who placed this order? I don't want this thing"],
        "Payment Information Security": ["I'm concerned about the security of my payment information"],
        "Privacy Settings Issues": ["I'm having issues with the privacy settings"]
    },
    "Account Management Issues": {
        "Login Issues": ["I'm unable to log into my account", "I can't log into my Samsung account on my mobile device"],
        "Password Retrieval": ["I can't retrieve my lost password"],
        "Verification Email": ["I didn't receive the account verification email"],
        "Account Information Modification": ["I'm unable to change my account information", "I need to update the name on my Samsung account", "Can I change my default billing or shipping address on file?", "I have a new e-mail address I'd like to move my Samsung account to."],
        "Account Creation": ["I experienced an issue during account creation"],
        "Account Deactivation or Deletion": ["I'm unable to deactivate or delete my account", "I want to delete my Samsung Account", "How do I delete my Samsung account, I no longer want it"],
        "Account Suspension or Ban": ["My account was suspended or banned"],
        "Linking Multiple Accounts": ["I had difficulty linking multiple accounts", "Can I tie all my Samsung accounts into one?"],
        "Two-factor Authentication": ["I'm unable to pass two-factor authentication, preventing log in to the site", "My phone number has changed and I can't get the code to log in.", "How do I pass 2 Factor if I no longer have my phone?"],
        "Unwanted Marketing Communications": ["I received unwanted marketing emails and text messages", "Stop Spamming me!", "I keep getting notifications to buy the new product on my phone"],
        "Preference Settings": ["I'm unable to set preferences in my account", "Can I change the type of e-mails I get", "How do I opt out of communications?"]
    },
    "Pre-Order Product Questions": {
        "Product Details Needed": ["I need details for Samsung mobile phones", "I need information about the newest Samsung Galaxy phone", "I need details about Samsung Galaxy Watch models", "I need information about Samsung home appliances", "How much are the newest devices?", "What are the costs for a new Samsung product?", "What's this going to cost me?", "What will I need to pay to purchase a new Samsung Product?", "I need details about Samsung consumer electronics", "I need information about Samsung televisions"],
        "Product Availability": ["When will this product be available again?", "I'm an international customer and need to know about product availability"],
        "Product Compatibility": ["I have questions about product compatibility", "Do these products work together?", "Does this work with my other Samsung products?"]
    },
    "Specific Issue Callouts": {
        "Sound Bar Discount": ["Wants to purchase the Samsung Q series 9.1.2 ch Dolby atoms soundbar system + rear speakers for a low price.", "Everyone is getting this sound bar at this price", "Samsung Q series 9.1.2 ch Dolby atoms soundbar system + rear speakers has a better employee offer and I would like the same discount.", "I want to buy HW-Q910C (2023) and get the lowest price, sainging $400."]
    },
    "Accessibility Feedback": {
        "Samsung Mobile Phones": ["I have feedback about accessibility options for Samsung mobile phones"],
        "Samsung Mobile Devices": ["I have feedback about accessibility options for other Samsung mobile devices"],
        "Samsung Tablets": ["I have feedback about accessibility options for Samsung tablets"],
        "Samsung Wearable Devices": ["I have feedback about accessibility options for Samsung wearable devices"],
        "Samsung Home Appliances": ["I have feedback about accessibility options for Samsung home appliances"],
        "Samsung Televisions": ["I have feedback about accessibility options for Samsung televisions"],
        "Samsung Consumer Electronics": ["I have feedback about accessibility options for Samsung consumer electronics"],
        "Samsung Computers and Laptops": ["I have feedback about accessibility options for Samsung computers and laptops"],
        "Samsung Monitors": ["I have feedback about accessibility options for Samsung monitors"]
    }
}
