default_categories = {
    "Website Content / App Critical Feedback": [
        "Help Pages and FAQs are hard to find",
        "Missing Product Details on Website",
        "Promotion Details are not clear",
        "Trade in Details are not clear",
        "Accessibility Options do not work",
        "Contact Support / Us options are hard to find",
        "My Orders Page Feedback",
        "Website Pop Up - Feedback",
        "Website Search Feature - Poor Results",
        "Website Product Compare Tool Feedback",
        "Outlet or Live Commerce Pop Up",
        "Mobile Webpage and App Problem",
        "Search Functionality Feedback",
        "Issues with finding the right product",
        "Slow and laggy Website performance",
        "Slow and laggy Mobile App Performance",
        "Stuck in Employee Store, Unable to Navigate Away",
        "Navigating Issues for Samsung Business Store",
        "Website Did not use my geo location accurately"
    ],
    "Product Support, Warranty and Repair (Care)": [
        "Loaner Phone Request for repair",
        "Product Registration issues",
        "Cost of Repair is too high",
        "Multiple Repair Requests",
        "Outside of Warranty Coverage",
        "Repair Lost in Transit",
	    "Care Plus + Subscription Coverage",
 	    "Need Help Troubleshooting Product",
        "Troubleshooting steps did not work",
        "Product Issues Were not Resolved by Care",
        "Technical Product Support Did not Follow Up",
        "Received Incorrect Troubleshooting from Product Tech Support",
        "Technical Product Support Hours Were Limited",
        "Repair Work Was Unsatisfactory",
        "Repair Took Too Long"
    ],
    "Return and Refund Issues": [
        "Return Refunding Processing Time",
        "Return Window Extension Request",
        "Return Shipping Label Request",
        "Shipping Label Print Requirement",
        "General Return Policy - How to Return?",
        "Wrong Return Refund Amount",
        "My Return Failed",
        "My Return was Unsent",
        "My Installation Charge Was Deducted From Return Refund",
        "Had Difficulty Initiating a Return",
        "I want a Refund",
        "I want an Exchange or Replacement",
        "Refund Was Not Issued After Return",
        "Unable to Request Return",
        "Restocking Fees Deducted From Refund",
        "Had Problems with Pickup for Return",
        "Refund Process Was Too Long",
        "Discrepancies in Partial Refunds",
        "Had Difficulty Tracking Returned Item",
        "Had Difficulties with International Return",
        "Product Was Damaged During Return Shipping",
        "Limited Options for Size/Color Exchanges",
        "Tax Exception - Tax Refund Needed",
        "Had Problems with Return Label"
    ],
    "Product Feedback": [
        "Charger Not Included",
        "Product Durability is poor",
        "General Product Feedback",
        "Mobile Applications Feedback",
        "Feedback on Pre-Installed Apps",
        "Product Missing Piece or Part"
    ],
    "Policy Feedback": [
        "Trade-In Chargeback Process Related",
        "Inability to Replace Items",
        "Concerns about Device Locking and Disabling Policies",
        "Feedback on Trade-In Process",
        "Shipping Policy Critiques",
        "Return Policy Critiques",
        "Accepted Payment Methods?",
        "Tax Exception Policy"
    ],
    "Post-Checkout Order Processing Issues": [
        "Cancelled Order - Buy Online Pickup in store",
        "Cancelled Order - Financing",
        "Cancelled Order - Fraud",
        "Cancelled Order - Unknown reason"
    ],
    "Post-Checkout Order Modification and Management": [
        "Unable to Change Available Delivery Options",
        "Unable to Cancel order",
        "Unable to Modify Products on order",
        "Unable to Add Product to Order",
        "Unable to Modify Payment Methods",
        "Cancel Order at Customer's Request"
    ],
    "General Feedback": [
        "Company Feedback",
        "Undefinable Feedback",
        "Warranty Feedback"
    ],
    "Shipping and Delivery Issues, Where is my Order?": [
        "Order has not shipped yet - Late",
        "Order has shipped - Late",
        "Order Lost in Transit, no Tracking Updates",
        "Delivery Date Keeps Changing and Getting Pushed Out",
        "Original Delivery Date Was Changed Immediately After Placing Order"
        "Product Missing from Shipment",
        "Wrong Product Received - Color",
        "Wrong Product Received - Model",
        "Wrong Product Received - General",
        "BESPOKE Panels - Not Shipped Delay",
        "Customization and Exclusive Color Time",
        "Buy Online Pickup in store - Best Buy Pickup Delay",
        "Buy Online Pickup in store - Best Buy Out of stock Delay",
        "Buy Online Pickup in store - Best Buy No Pick Up Ready Confirmation",
        "Order Delivered, but not Received",
        "Defective Product Received, DOA",
        "No Tracking Information- UPS",
        "No Tracking Information- AGS",
        "No Tracking Information- Buy Online Pickup in store",
        "No Tracking Information- FedEx",
        "No Tracking Information- Forward Air",
        "No Tracking Information- RXO",
        "No Tracking Information- Unknown",
        "Received Damaged Product",
        "Delivery Date was Missed",
        "Inaccurate Delivery Tracking",
        "Limited Delivery Zones",
        "Delivered to Wrong Location or Address",
        "Delivery Attempted, but not completed"
    ],
    "Customer Service and Contact Feedback": [
        "Agent Unable to Solve Issue",
        "Service Level Expectation",
        "Agent Knowledge is lacking",
        "Agent Ownership and follow up is poor",
        "Technical Issues - Time to Resolve",
        "Contact Disconnected, no callback",
        "Long Wait Times for Support Response",
        "Put on Hold for Far Too Long",
        "Language Barrier with Support Staff, Difficult to Understand",
        "Too Much Time Between Chat Replies",
        "Lack of Empathy from Support Staff",
	    "Supervisor was Not Helpful",
	    "Agent Would Not Escalate or Let Me Talk to Supervisor",
	    "At This Point, Immediate Supervisor or Leader is Required"
    ],
    "Checkout and Cart Issues": [
        "Unable to checkout - Payment Issue",
	    "Delivery Date is Too Far Out",
        "Verizon, unable to log into Carrier Website",
	    "T-Mobile, unable to log into Carrier Website",
	    "ATT / AT&T, unable to log into Carrier Website",
        "Price Changing in Cart and Checkout",
        "Error Message Preventing Checkout",
        "Finance Offer Changes in Cart and Checkout",
        "Promotion EPP Issue - Employee Purchase Program Discount",
	    "Promotion EPP Issue - Student Discount",
        "Promotion EPP Issue - First Responder Discount",
        "Payment Issue - Samsung Financing",
	    "Payment Issue - Carrier Financing",
	    "Payment Issue - Credit Card",
	    "Payment Issue - Apple Pay, PayPal",
	    "Payment Issue - Affirm Financing",
        "Payment Issue - Unknown",
	    "Payment Issue - Financing Credit Available, but Not Working",
        "Promotion Issue - Promotion Not Applied",
        "Samsung Rewards - Not Applied",
        "Split Payment Not Working",
        "Unable to checkout - Technical Issue",
	    "$50 dollar Reserve Credit - Not Applying",
	    "$50 dollar Reserve Credit - Not Received",
        "Limited Shipping Methods and speeds",
        "Unable to Verify Shipping Address",
        "Unable to Modify Quantity"
        ],
    "Installation Problems": [
        "Complex Installation Process",
        "Installation Appointment was missed",
	    "Installers Arrived Late for the appointment",
        "Missing Installation Parts",
        "Installers Damaged my Home Appliance product",
	    "Installers Damaged my Home or Property",
	    "Installers Damaged my TV / Television product",
        "Rude Installation Staff",
        "Issues with product after it was installed",
	    "Installation Did Not Happen At Delivery"
    ],
    "Privacy & Security Concerns": [
        "Concerns about Data Security and Privacy",
        "Lack of Transparency in Data Usage",
        "Experiences of Scams & Phishing",
        "Payment Information Security Concerns",
	    "Issues with Privacy Settings"
    ],
    "Account Management Questions and Issues": [
        "Unable to Log into my Account",
        "Could Not Retrieve Lost Password",
        "Didn't Receive Account Verification Email",
        "Unable to Change Account Information",
        "Experienced Issue During Account Creation",
        "Unable to Deactivate Account",
        "Account Was Suspended or Banned Unexpectedly",
        "Had Difficulty Linking Multiple Accounts",
        "Received Unwanted Marketing Emails and Text Messages",
        "Unable to Set Preferences in Account"
    ],
    "Product Questions Before Placing Order": [
	    "Product Details - Mobile Phones",
	    "Product Details - the Newest Phone Flagship",
	    "Product Details - Available Mobile Accessories and Cases for Newest Phone",
	    "Product Details - Home Appliances",
	    "Product Details - Consumer Electronics",
	    "Product Details - Televisions (TVs)",
	    "Product Comparisons for Mobile Products",
	    "When will this Product be Available Again?",
	    "Need Help Choosing The Right Product"
    ],
    "Discount and Promotion Questions Before Placing Order": [
	    "Best Discount and Promo for Mobile Phone?",
	    "Best Discount and Promo for TV?",
	    "Best Discount and Promo for Home Appliances?",
	    "How do I Apply Samsung Rewards?",
	    "Discounts for Buying in Bulk?",
	    "Applying Add-On Credit to my Order",
	    "Additional Discounts for accessories",
	    "Details Needed for Memory Upgrade"
    ],
    "Post-Order Promotion and Subscription Questions": [
        "How do I - YouTube Premium",
        "How do I - Spotify",
        "How do I - Art Store",
        "How do I - Adobe Light Room",
        "How do I - Microsoft OneDrive",
        "How do I - Sirius XM Radio",
        "$100, $150, $200 ECertificate Redemption - When is it sent?",
        "$100, $150, $200 ECertificate Redemption - How to use?",
        "$100, $150, $200 ECertificate Redemption - Must Use it Now?"
    ],
    "Trade-In Program Questions and Issues": [
        "What is Cracked Screen Offer?",
        "How to Check if Device Qualifies",
        "How much is This Device Worth?",
        "Trade-In Values Change in Cart / Checkout",
        "Trade-In Bill Credits are Different",
        "Trade-In Failed and I was Charged",
        "Possible to Trade-in Multiple Devices",
        "Trade-in Credit What if it is Returned?",
        "Disputing Trade-in Results"
    ],
}
