default_categories = {
    "Website Content / App Critical Feedback": {
        "Help Pages and FAQs are hard to find": ["Help Pages", "FAQs"],
        "Missing Product Details on Website": ["Product Details", "Website"],
        "Promotion Details are not clear": ["Promotion Details", "Website"],
        "Trade in Details are not clear when adding trade-in": ["Trade-in Details", "Website"],
        "Accessibility Options do not work": ["Accessibility Options", "Website"],
        "Contact Support / Us options are hard to find": ["Contact Support", "Website"],
        "My Orders Page Feedback": ["My Orders Page", "Website"],
        "Website Pop Up - Feedback": ["Website Pop Up", "Website"],
        "Website Search Feature - Poor Results": ["Search Feature", "Website"],
        "Website Product Compare Tool Feedback": ["Product Compare Tool", "Website"],
        "Outlet or Live Commerce Pop Up": ["Outlet Pop Up", "Website"],
        "Mobile Webpage and App Problem": ["Mobile Webpage", "App Problem"],
        "Search Functionality Feedback": ["Search Functionality", "Website"],
        "Issues with finding the right product": ["Finding Product", "Website"],
        "Slow and laggy Website performance": ["Website Performance", "Lag"],
        "Slow and laggy Mobile App Performance": ["Mobile App Performance", "Lag"],
        "Stuck in Employee Store, Unable to Navigate Away": ["Employee Store", "Navigation"],
        "Navigation Issues for Samsung Business Store": ["Business Store", "Navigation"],
        "The Website crashed frequently, making browsing and ordering a difficult process": ["Website Crash", "Ordering"],
        "Website Did not use my geo location accurately": ["Geo Location", "Website"]
    },
    "Product Support, Warranty and Repair (Care)": {
        "Loaner Phone Request for repair": ["Loaner Phone", "Repair"],
        "Product Registration issues - unable to register Samsung Product": ["Product Registration", "Issue"],
        "Cost of Repair is too high": ["Repair Cost", "High"],
        "Have to make Multiple Repair Requests": ["Multiple Repair Requests", "Issue"],
        "Outside of Warranty Coverage - Unable to have device fixed": ["Warranty Coverage", "Issue"],
        "Repair Lost in Transit": ["Repair Lost", "Transit"],
        "Care Plus + Subscription Coverage": ["Care Plus", "Subscription Coverage"],
        "Need Help Troubleshooting Product": ["Troubleshooting Help", "Product"],
        "Troubleshooting steps did not work": ["Troubleshooting Steps", "Issue"],
        "Product Issues Were not Resolved by Care": ["Product Issues", "Not Resolved"],
        "Technical Product Support Did not Follow Up": ["Technical Support", "No Follow Up"],
        "Received Incorrect Troubleshooting from Product Tech Support": ["Incorrect Troubleshooting", "Tech Support"],
        "Technical Product Support Hours Were Limited": ["Limited Tech Support Hours", "Issue"],
        "Repair Work Was Unsatisfactory": ["Unsatisfactory Repair Work", "Issue"],
        "Repair Work Took Too Long": ["Long Repair Time", "Issue"]
    },
    "Return and Refund Issues": {
        "Return Refund Processing Time after return delivered": ["Return Refund Processing Time", "Return Delivered"],
        "Return Window Extension Request to ship return later": ["Return Window Extension", "Return Shipping"],
        "Return Shipping Label Request, return already requested": ["Return Shipping Label", "Return Requested"],
        "Customer is frustrated that they need to wait for a return and refund before they can place a new order": ["Wait for Refund", "New Order"],
        "Shipping Label Print Requirement, need to print label": ["Shipping Label Print", "Return"],
        "General Return Policy - How to Return, restrictions?": ["General Return Policy", "How to Return"],
        "Wrong Return Refund Amount received after Return": ["Wrong Refund Amount", "Return"],
        "My Return Failed and I did not receive a refund": ["Failed Return", "No Refund"],
        "My Return failed and it was Unsent": ["Unsent Return", "Issue"],
        "My Installation Charge Was Deducted From Return Refund": ["Installation Charge Deducted", "Return Refund"],
        "Had Difficulty Initiating a Return, no return option available": ["Difficulty Initiating Return", "Issue"],
        "I want a Refund for an order I placed": ["Refund Request", "Order"],
        "I want an Exchange or Replacement": ["Exchange or Replacement", "Request"],
        "Refund Was Not Issued After Return": ["Refund Not Issued", "Return"],
        "Restocking Fees Deducted From Refund": ["Restocking Fees", "Refund"],
        "Needs to have order picked up for Return, unable to ship": ["Pick Up Return", "Shipping"],
        "Discrepancies in Partial Refunds": ["Partial Refunds", "Discrepancies"],
        "Had Difficulty Tracking shipped Returned Item": ["Difficulty Tracking Return", "Shipped"],
        "Had Difficulties with International Return": ["International Return", "Issues"],
        "Product Was Damaged During Return Shipping": ["Damaged During Return", "Shipping"],
        "Tax Exception - Tax Refund Needed": ["Tax Exception", "Tax Refund"],
        "Had Problems with Return Label": ["Return Label Problems", "Issue"]
    },
    "Product Feedback": {
        "Charger Not Included with my order": ["Charger Not Included", "Order"],
        "Product Durability is poor": ["Poor Product Durability", "Issue"],
        "General Product Feedback": ["General Product Feedback"],
        "Mobile Applications Feedback": ["Mobile Applications Feedback"],
        "Feedback on Pre-Installed Apps": ["Pre-Installed Apps Feedback"],
        "There is still no headphone / speaker port on the newest phones.": ["No Headphone Port", "Newest Phones"],
        "The product that I wanted was out of stock by the time I tried to order it.": ["Out of Stock Product", "Order"],
        "Product Missing Piece or Part": ["Missing Product Piece", "Part"]
    },
    "Policy Feedback": {
        "Customer does not like the Trade-In Chargeback Process": ["Trade-In Chargeback Process", "Issue"],
        "Customer is frustrated at the Inability to Replace Items": ["Inability to Replace Items", "Issue"],
        "Concerns about Device Knox Locking and Disabling Policies": ["Device Knox Locking", "Disabling Policies"],
        "Customer is providing Shipping Policy Critiques": ["Shipping Policy Critiques", "Feedback"],
        "Customer is providing Return Policy Critique": ["Return Policy Critique", "Feedback"],
        "What are the Accepted Payment Methods?": ["Accepted Payment Methods", "Question"],
        "General questions about the Tax Exception Policy": ["Tax Exception Policy", "Questions"]
    },
    "Post-Checkout Order Processing Issues": {
        "My Order was cancelled - Buy Online Pickup in store": ["Order Cancelled - Buy Online Pickup", "Store"],
        "My Order was cancelled - Financing": ["Order Cancelled - Financing"],
        "My Order was cancelled - Fraud": ["Order Cancelled - Fraud"],
        "My Order was cancelled - Unknown reason": ["Order Cancelled - Unknown Reason"],
        "My order was cancelled several times, I attempted to order again and again.": ["Order Cancelled Multiple Times", "Issue"]
    },
    "Post-Checkout Order Modification and Management": {
        "Unable to Change Available Delivery Options": ["Change Delivery Options", "Issue"],
        "Unable to Cancel order": ["Unable to Cancel Order", "Issue"],
        "Unable to Modify Products on order": ["Unable to Modify Products", "Issue"],
        "Unable to Add Product to Order": ["Unable to Add Product", "Issue"],
        "Unable to Modify Payment Methods": ["Modify Payment Methods", "Issue"],
        "I had to cancel my order to make any changes, such as a different color.": ["Order Cancelled for Changes", "Issue"],
        "Customer wants to cancel an order they placed": ["Customer Wants to Cancel Order", "Issue"]
    },
    "Shipping and Delivery Issues, Where is my Order?": {
        "Where is my Order - Order has not shipped yet - Late": ["Order Not Shipped - Late", "Where is my Order"],
        "Customer wants to know about when an order will ship and be delivered": ["Order Ship and Delivery", "Questions"],
        "Where is my Order - Order has shipped - Late": ["Order Shipped - Late", "Where is my Order"],
        "Where is my Order - Order Lost in Transit, no Tracking Updates": ["Order Lost in Transit", "No Tracking Updates"],
        "Where is my Order - Delivery Date Keeps Changing and Getting Pushed Out": ["Delivery Date Changes", "Pushed Out"],
        "Original Delivery Date Was Changed Immediately After Placing Order": ["Delivery Date Changed", "Immediately"],
        "Where is my Order - Product Missing from Shipment": ["Product Missing from Shipment", "Where is my Order"],
        "Wrong Product Received - Color": ["Wrong Product Received - Color", "Issue"],
        "Wrong Product Received - Model": ["Wrong Product Received - Model", "Issue"],
        "Wrong Product Received - General": ["Wrong Product Received", "Issue"],
        "BESPOKE Fridge / Refrigerator Panels - Not Shipped Delay": ["BESPOKE Fridge Panels", "Not Shipped Delay"],
        "Customization and Exclusive Color delivery delay Time, weeks": ["Customization Delivery Delay", "Weeks"],
        "Buy Online Pickup in store - Best Buy Pickup Delay": ["Buy Online Pickup - Best Buy Delay", "Store"],
        "Buy Online Pickup in store - Best Buy Out of stock Delay": ["Buy Online Pickup - Best Buy Out of Stock", "Store"],
        "Buy Online Pickup in store - Best Buy No Pick Up Ready Confirmation": ["Buy Online Pickup - No Confirmation", "Store"],
        "Where is my order - Order Delivered, but not Received": ["Order Delivered - Not Received", "Where is my Order"],
        "Defective Product delivered and Received, DOA, unit does not work": ["Defective Product Delivered", "Received"],
        "No Tracking Information - UPS": ["No Tracking Information - UPS", "Shipping"],
        "No Tracking Information - AGS": ["No Tracking Information - AGS", "Shipping"],
        "No Tracking Information - Buy Online Pickup in store": ["No Tracking Info - Buy Online Pickup", "Store"],
        "No Tracking Information - FedEx": ["No Tracking Information - FedEx", "Shipping"],
        "No Tracking Information - Forward Air": ["No Tracking Information - Forward Air", "Shipping"],
        "No Tracking Information - RXO": ["No Tracking Information - RXO", "Shipping"],
        "No Tracking Information - Unknown": ["No Tracking Information - Unknown", "Shipping"],
        "Received Damaged Product, scratched, dented, etc": ["Received Damaged Product", "Issue"],
        "Where is my Order - Delivery Date was Missed": ["Delivery Date Missed", "Where is my Order"],
        "Where is my Order - Inaccurate Delivery Tracking": ["Inaccurate Delivery Tracking", "Where is my Order"],
        "Unable to checkout - Limited Delivery Zones, shipping restriction": ["Limited Delivery Zones", "Shipping Restriction"],
        "Where is my Order - Delivered to Wrong Location or Address": ["Delivered to Wrong Location", "Where is my Order"],
        "Where is my Order - Delivery Attempted, but not completed": ["Delivery Attempted - Not Completed", "Where is my Order"]
    },
    "Customer Service and Contact Feedback": {
        "Customer Service Agent Unable to Solve Issue": ["CS Agent Unable to Solve Issue", "Customer Service"],
        "Service Level Expectation, why did it take so long to connect?": ["Service Level Expectation", "Long Connection Time"],
        "Customer Service Agent Knowledge is lacking": ["CS Agent Knowledge Lacking", "Customer Service"],
        "Customer Service Agent Ownership and follow up is poor": ["CS Agent Ownership and Follow Up", "Customer Service"],
        "Technical Issues - too much Time to Resolve": ["Technical Issues - Long Resolution Time", "Customer Service"],
        "Contact Disconnected, no callback or e-mail received": ["Contact Disconnected - No Callback", "Customer Service"],
        "Long Wait Times for Agent Support Response": ["Long Wait Times - Agent Support", "Customer Service"],
        "Put on Hold for Far Too Long during conversation": ["Put on Hold - Long Time", "Customer Service"],
        "Language Barrier with Customer Support Staff, Difficult to Understand": ["Language Barrier - Difficult to Understand", "Customer Service"],
        "Too Much Time Between Chat Replies": ["Too Much Time Between Chat Replies", "Customer Service"],
        "Lack of Empathy from Customer Support Staff": ["Lack of Empathy - Support Staff", "Customer Service"],
        "Supervisor was Not Helpful during call or chat": ["Unhelpful Supervisor", "Customer Service"],
        "Agent Would Not Escalate or Let Me Talk / chat with Supervisor": ["Agent Not Escalating", "Customer Service"],
        "Customer is stating they will go to a competitor, Apple, as a result of poor treatment.": ["Customer Going to Competitor", "Customer Service"],
        "Customer service Agent is repeating the same troubleshooting or advice and it continues to not be effective.": ["CS Agent Repeating Troubleshooting", "Customer Service"],
        "Customer service is closed, unable to call or chat, no one is available to help me.": ["Closed Customer Service", "Customer Service"],
        "At This Point, Immediate Supervisor or Leader is Required": ["Immediate Supervisor Required", "Customer Service"]
    },
    "Checkout and Cart Issues": {
        "Unable to checkout - Payment Issue": ["Unable to Checkout - Payment Issue", "Issue"],
        "Customer does not want to order because delivery will take too long": ["Customer Doesn't Want to Order", "Long Delivery"],
        "Verizon, unable to log into Carrier Website to complete checkout": ["Verizon - Unable to Log in", "Carrier Website"],
        "T-Mobile, unable to log into Carrier Website to complete checkout": ["T-Mobile - Unable to Log in", "Carrier Website"],
        "ATT / AT&T, unable to log into Carrier Website to complete checkout": ["ATT / AT&T - Unable to Log in", "Carrier Website"],
        "Price Changing in Cart and Checkout when I try to order": ["Price Changing in Cart and Checkout", "Issue"],
        "Price in cart is higher than the product page, click to order one price and higher price is given when ordering": ["Price in Cart Higher", "Issue"],
        "Error Message Preventing Checkout": ["Error Message - Preventing Checkout", "Issue"],
        "Finance Offer Changes in Cart and Checkout": ["Finance Offer Changes", "Cart and Checkout"],
        "Promotion EPP Issue - Employee Purchase Program Discount": ["Promotion EPP Issue - Employee Purchase Program", "Discount"],
        "Promotion EPP Issue - Student or Teacher Discount": ["Promotion EPP Issue - Student or Teacher Discount", "Discount"],
        "Promotion EPP Issue - First Responder or Military Discount": ["Promotion EPP Issue - First Responder or Military", "Discount"],
        "Payment Issue - Samsung Financing Customer unable to checkout": ["Payment Issue - Samsung Financing", "Unable to Checkout"],
        "Payment Issue - Carrier Financing preventing placing order": ["Payment Issue - Carrier Financing", "Preventing Order"],
        "Payment Issue - Credit Card unable to place order": ["Payment Issue - Credit Card", "Unable to Place Order"],
        "Payment Issue - Apple Pay, PayPal is not working": ["Payment Issue - Apple Pay, PayPal", "Not Working"],
        "Payment Issue - Affirm Financing is not working": ["Payment Issue - Affirm Financing", "Not Working"],
        "Payment Issue - Klarno Financing is not available": ["Payment Issue - Klarno Financing", "Not Available"],
        "Payment Issue - Unknown Payment method type": ["Payment Issue - Unknown Method", "Issue"],
        "Payment Issue - Financing Credit Available, but Not Working": ["Payment Issue - Financing Credit", "Not Working"],
        "Promotion Issue - Promotion Not Applied or promo is invalid": ["Promotion Issue - Not Applied", "Invalid Promo"],
        "Reward Points are Not Applied to my order.": ["Reward Points Not Applied", "Order"],
        "Split Payment Not Working, want multiple payment options": ["Split Payment Not Working", "Multiple Payment Options"],
        "Unable to checkout - Technical Issue": ["Unable to Checkout - Technical Issue", "Issue"],
        "$50 dollar Reserve Reservation promo Credit - Not Applying or invalid": ["$50 Reserve Reservation Credit - Not Applying", "Invalid"],
        "$50 dollar Reserve Reservation Reserve Credit - Not Received": ["$50 Reserve Reservation Credit - Not Received", "Issue"],
        "Limited Shipping Methods and speeds": ["Limited Shipping Methods", "Issue"],
        "Unable to Verify Shipping Address error message received at checkout": ["Unable to Verify Shipping Address", "Error Message"],
        "Customer is able to place their order, but it is cancelled repeatedly, regardless of payment method.": ["Order Cancelled Repeatedly", "Issue"],
        "My payment method was charged, despite the order being cancelled or not placed at all.": ["Payment Method Charged - Cancelled Order", "Issue"],
        "When I place an order, or attempt ordering multiple times, the order is cancelled shortly after.": ["Order Cancelled After Placement", "Issue"],
        "All items/products are removed from cart, difficult to make changes to order prior to it being placed.": ["Items Removed from Cart", "Issue"],
        "Samsung Order Cancelled Notification Sent Repeatedly after I make an order.": ["Order Cancelled Notification Sent Repeatedly", "Issue"],
        "Unable to Modify Quantity of the order I want to place": ["Unable to Modify Quantity", "Order"]
    },
    "Installation Problems": {
        "Complex Installation Process, multiple visits by installers required": ["Complex Installation Process", "Multiple Visits"],
        "Installation Appointment was missed by installers": ["Installation Appointment Missed", "Installers"],
        "Installers Arrived Late for the appointment": ["Installers Arrived Late", "Appointment"],
        "Missing Installation Parts, so unable to install products": ["Missing Installation Parts", "Install Products"],
        "Installers Damaged my Home Appliance product": ["Installers Damaged Home Appliance", "Issue"],
        "Installers Damaged my Home or Property": ["Installers Damaged Home or Property", "Issue"],
        "Installers Damaged my TV / Television product": ["Installers Damaged TV / Television", "Issue"],
        "Rude Installation Staff at the time of service": ["Rude Installation Staff", "Issue"],
        "Issues with product after it was installed": ["Product Issues After Installation", "Issue"],
        "Installation Did Not Happen At Delivery": ["Installation Did Not Happen At Delivery", "Issue"]
    },
    "Privacy & Security Concerns": {
        "Concerns about Website Data Security and Privacy": ["Website Data Security and Privacy", "Concerns"],
        "Lack of Transparency in Data Usage": ["Lack of Transparency in Data Usage", "Concerns"],
        "Experiences of Scams & Phishing": ["Scams & Phishing", "Experiences"],
        "Payment Information Security Concerns": ["Payment Information Security", "Concerns"],
        "Issues with Privacy Settings": ["Privacy Settings Issues", "Concerns"]
    },
    "Account Management Questions and Issues": {
        "Unable to Log into my Account": ["Unable to Log into Account", "Issue"],
        "Could Not Retrieve Lost Password": ["Could Not Retrieve Lost Password", "Issue"],
        "Did not Receive Account Verification Email": ["Did not Receive Verification Email", "Issue"],
        "Unable to Change Account Information": ["Unable to Change Account Info", "Issue"],
        "Experienced Issue During Account Creation": ["Issue During Account Creation", "Issue"],
        "Unable to Deactivate or Delete Account": ["Unable to Deactivate or Delete Account", "Issue"],
        "Account Was Suspended or Banned Unexpectedly": ["Account Suspended or Banned", "Issue"],
        "Had Difficulty Linking Multiple Accounts": ["Difficulty Linking Multiple Accounts", "Issue"],
        "Unable to pass two-factor (2 factor) authentication, preventing log in to site.": ["Two-factor Authentication Issue", "Log in"],
        "Unable to log into my Samsung account on my mobile cell device.": ["Unable to Log into Samsung Account", "Mobile Device"],
        "Received Unwanted Marketing Emails and Text Messages": ["Unwanted Marketing Emails and Text Messages", "Issue"],
        "Unable to Set Preferences in Account": ["Unable to Set Preferences", "Account"]
    },
    "Product Questions Before Placing Order": {
        "Product Details Needed - Samsung Mobile Phones": ["Product Details Needed - Samsung Mobile Phones", "Product"],
        "Product Details Needed - the Newest Samsung Galaxy Phone Flagship": ["Product Details Needed - Newest Galaxy Phone", "Product"],
        "Product Details Needed - Samsung Galaxy Watch 3, 4, 5, 40MM, 42MM, 44MM, 45MM": ["Product Details Needed - Samsung Galaxy Watches", "Product"],
        "Product Details Needed - Samsung Home Appliances": ["Product Details Needed - Samsung Home Appliances", "Product"],
        "Product Details Needed - Samsung Consumer Electronics": ["Product Details Needed - Samsung Consumer Electronics", "Product"],
        "Product Details Needed - Samsung Televisions (TVs)": ["Product Details Needed - Samsung Televisions", "Product"],
        "Product Comparisons for Mobile Products Needed": ["Product Comparisons for Mobile Products", "Product"],
        "When will this Product be Available Again?": ["Product Availability Inquiry", "Product"],
        "Product Compatibility Questions": ["Product Compatibility Questions", "Product"],
        "Product Availability for International Customers": ["Product Availability for International Customers", "Product"]
    },
    "Accessibility Options and Features Feedback": {
        "Accessibility Options and Features Feedback - Samsung Mobile Phones": ["Accessibility Options - Samsung Mobile Phones", "Feedback"],
        "Accessibility Options and Features Feedback - Samsung Mobile Devices": ["Accessibility Options - Samsung Mobile Devices", "Feedback"],
        "Accessibility Options and Features Feedback - Samsung Tablets": ["Accessibility Options - Samsung Tablets", "Feedback"],
        "Accessibility Options and Features Feedback - Samsung Wearable Devices": ["Accessibility Options - Samsung Wearable Devices", "Feedback"],
        "Accessibility Options and Features Feedback - Samsung Home Appliances": ["Accessibility Options - Samsung Home Appliances", "Feedback"],
        "Accessibility Options and Features Feedback - Samsung Televisions (TVs)": ["Accessibility Options - Samsung Televisions", "Feedback"],
        "Accessibility Options and Features Feedback - Samsung Consumer Electronics": ["Accessibility Options - Samsung Consumer Electronics", "Feedback"],
        "Accessibility Options and Features Feedback - Samsung Computers and Laptops": ["Accessibility Options - Samsung Computers and Laptops", "Feedback"],
        "Accessibility Options and Features Feedback - Samsung Monitors": ["Accessibility Options - Samsung Monitors", "Feedback"]
    },
    "Others": {
        "Other Category (Not Listed Above)": ["Other Category (Not Listed Above)"]
    }
}
