default_categories = {
    "Product Discovery & Selection": [
        "Had Trouble Searching for a Specific Product",
        "Found Product Information Unclear or Incomplete",
        "Lacked Enough Information in Product Reviews",
        "Product Specifications Seemed Inaccurate",
        "Product Images Seemed Outdated",
        "Couldn't Determine if Product Was in Stock",
        "Struggled to Compare Different Products",
        "Wanted Product Wasn't Available",
        "Confused About Different Product Options",
        "Overwhelmed by Too Many Product Options",
        "Product Filters Didn't Help Narrow Down Choices",
        "Products Seemed Misclassified",
        "Product Recommendations Didn't Seem Relevant",
        "Had Trouble Saving Favorite Products",
        "Didn't Get Enough Information from Product Manufacturer"
    ],
    "Stock & Availability": [
        "Product Was Out of Stock",
        "Had to Wait Too Long for backorder",
        "Product Was Excluded from Promotions",
        "Limited Availability for Deals",
        "Deal Restrictions Were Based on My Location",
        "Was Restricted on the Quantity I Could Purchase"
    ],
    "Product Quality": [
        "Unhappy with Product Quality",
        "Product Battery Life is below Expectations",
        "Regret Buying Product Due to Quality Issues",
        "Product Broke Sooner than it should have"
    ],
    "Pricing & Promotions": [
        "Promotion Didn't Apply to My Purchase",
        "Promotion Terms Were Unclear",
        "Saw Outdated Promotion Still Being Displayed",
        "Deal Fulfillment Didn't Go Through",
        "Had Trouble Locating Promotions on the Site",
        "Faced Issues When Applying Discounts",
        "Noticed Inconsistencies in Pricing",
        "Discounts Were Not Clearly Visible",
        "Encountered Problems with Membership Program",
        "Felt Pricing Was Deceptive",
        "Confused Over How Bulk Discounts Applied",
        "Lacked Information on Seasonal Sales",
        "Faced Problems with Referral Program",
        "Trade-in Credit Not Applied",
        "Encountered Unexpected Fees"
    ],
    "Pre-Order & Delivery Planning": [
        "Encountered Problems During Pre-Order",
        "Experienced Delays in Pre-Order",
        "Received Inaccurate Pre-Order Information",
        "Pre-Order Was Cancelled Unexpectedly",
        "Faced Unexpected Charges for Pre-Order",
        "Didn't Receive Updates on Pre-Order Status",
        "Had Issues with Delivery of Pre-Ordered Product",
        "Pre-Order Process Was Confusing",
        "Couldn't Pre-Order the Product",
        "Delivery Timelines Were Unclear",
        "Mismatch Between Pre-Ordered and Delivered Product",
        "Had Issues with Partial Payments",
        "Had Trouble Modifying Pre-Order Details",
        "Limited Options for Delivery Date",
        "Had Issues with Delivering Split Orders"
    ],
    "Website & App Interface": [
        "Experienced Glitches on Website",
        "Website Performance Was Slow",
        "Had Trouble Navigating the Interface",
        "Found Broken Links on Website",
        "Couldn't Locate Features on Website",
        "User Interface Was Confusing",
        "Website Didn't Adjust Well to My Location"
    ],
    "Order Management & Checkout": [
        "Experienced Glitches During Ordering",
        "Checkout Process Was Too Lengthy",
        "Payment Failed During Checkout",
        "Had Issues with Shopping Cart",
        "Couldn't Modify My Order",
        "Couldn't Cancel My Order",
        "Didn't Receive Order Confirmation",
        "My Order Was Cancelled Unexpectedly",
        "No Option for Express Checkout",
        "Price Changed at Checkout",
        "Items in Cart were Not Saved",
        "My Order Keeps Getting Cancelled",
        "Had Problems Reviewing Order Before Checkout"
    ],
    "Payment & Billing": [
        "Was Charged Incorrectly",
        "Payment Was Declined During Checkout",
        "Financing Was Declined During Checkout",
        "Was Confused About Applying Discount/Coupon",
        "Payment Options Were Limited",
        "Had Difficulty Saving Payment Information",
        "Noticed Suspicious Charges",
        "Had Problems with Installment Payment",
        "Had Difficulty Splitting Payment",
        "Concerned About Data Security During Payment",
        "Had Problems with Tax Calculation"
    ],
    "Delivery & Shipping": [
        "Delivery Was Late",
        "Product Wasn't Delivered",
        "Received Wrong Product",
        "Product Was Damaged Upon Arrival",
        "Delivery Was Incomplete",
        "Had Problems Tracking My Delivery",
        "Had Issues with the Courier Service",
        "Delivery Options Were Limited",
        "Product Packaging Was Poor",
        "Had Difficulties with International Shipping",
        "Delivery Restrictions Were Based on My Zip Code",
        "Didn't Receive Updates on Delivery Status",
        "Limited Options for Same-Day/Next-Day Delivery",
        "Fragile Items Were Handled Poorly During Delivery",
        "Didn't Get Adequate Communication from Courier",
        "Delivery Address Was Incorrect"
    ],
    "Store & Pickup Services": [
        "Had Trouble Locating Stores",
        "Mismatch Between Chosen and Actual Pickup Location",
        "Had to Change Pickup Store",
        "Instructions for In-Store Pickup Were Unclear",
        "Received Poor Support In-Store",
        "Waited Too Long for Pickup",
        "Had Difficulty Scheduling Pickup Time",
        "Confused About Store Purchase Return Policy",
        "Had Difficulty Accessing Order History"
    ],
    "Product Installation & Setup": [
        "Had Difficulty During Product Installation",
        "Installation Instructions Were Missing",
        "Had Problems with Product After Installation",
        "Didn't Get Enough Assistance During Setup",
        "Received Incorrect Assembly Parts",
        "Had Issues with Product Compatibility",
        "Faced Unexpected Requirements During Setup",
        "Mismatch Between Product and Manual",
        "Lacked Technical Support",
        "Didn't Find Troubleshooting Guides Helpful",
        "Needed Professional Installation",
        "Needed Additional Tools Unexpectedly",
        "Had Problems After Setup Update"
    ],
    "Returns, Refunds & Exchanges": [
        "Had Difficulty Initiating a Return",
        "I want a Refund",
        "I want an Exchange",
        "Refund Wasn't Issued After Return",
        "Was Ineligible for Return",
        "Confused Over Restocking Fees",
        "Had Problems with Pickup for Return",
        "Had to wait too long for product refund",
        "Discrepancies in Partial Refunds",
        "Had Difficulty Tracking Returned Item",
        "Had Difficulties with International Return",
        "Product Was Damaged During Return Shipping",
        "Limited Options for Size/Color Exchanges",
        "Had Problems with Return Label"
    ],
    "Pre-Purchase Assistance": [
        "Had Trouble Getting Help Before Buying",
        "Couldn't Find Enough Product Information or Advice",
        "Customer Service Took Too Long to Respond",
        "Received Incorrect Information",
        "Support Wasn't Helpful with Promotions or Deals",
        "Had Trouble Scheduling Store Visits or Pickups",
        "Got Inconsistent Information from Different Agents"
    ],
    "Post-Purchase Assistance": [
        "Had Trouble Contacting Support After Purchase",
        "Post-Purchase Customer Service Response Was Slow",
        "Issues Were Not Resolved by Customer Service",
        "Didn't Get Enough Help Setting Up or Using Product",
        "Trouble Understanding Product Features Due to Poor Support",
        "Had Difficulty Getting Assistance During Product Installation",
        "Had Trouble Contacting Customer Service for Delivery-Related Issues",
        "Had Trouble Escalating Issues",
        "Self-Service Options Were Limited"
    ],
    "Technical/Product Support": [
        "Need Help Troubleshooting Product",
        "Had Trouble Receiving Technical Support",
        "Troubleshooting Advice from Tech Support Wasn't Helpful",
        "Technical Issues Weren't Resolved by Support",
        "Technical Instructions Were Difficult to Understand",
        "Tech Support Didn't Follow Up",
        "Received Incorrect Advice from Tech Support",
        "Automated Technical Support Was Problematic",
        "Not happy about limitations of warranty support",
        "Technical Support Hours Were Limited"
    ],
    "Repair Services": [
        "Had Trouble Scheduling Repair",
        "Repair Work Was Unsatisfactory",
        "Repair Work Took Too Long",
        "Parts Replacement Took Too Long",
        "Had to wait too long for Defective Product Replacement",
        "Confused About Repair Charges",
        "No Follow-Up After Repair",
        "Received Incorrect Advice from Repair Service",
        "Repair Service Left Without Fixing Issue",
        "Had to wait too long for Product Repair",
        "Repair Resolution Process Was Inefficient",
        "Bad Quality Product Required Expensive Repair"
    ],
    "Account Management": [
        "Had Difficulty Logging In",
        "Couldn't Retrieve Lost Password",
        "Didn't Receive Account Verification Email",
        "Changing Account Information",
        "Had Problems with Account Security",
        "Experienced Glitches During Account Creation",
        "Not Able to Deactivate Account",
        "Had Issues with Privacy Settings",
        "Account Was Suspended or Banned Unexpectedly",
        "Had Difficulty Linking Multiple Accounts",
        "Didn't Get Email Notifications",
        "Had Issues with Subscription Management",
        "Couldn't Track Order History",
        "Received Unwanted Marketing Emails",
        "Trouble Setting Preferences in Account"
    ],
}
