default_categories = {
    "Website Content / App Critical Feedback": {
        "Help Pages and FAQs are hard to find": ["I can't find the help pages", "Where are the FAQs?"],
        "Missing Product Details on Website": ["The product details are missing on the website", "I can't find information about the product on the website"],
        "Promotion Details are not clear": ["The promotion details are unclear", "I don't understand the promotion details on the website"],
        "Trade in Details are not clear when adding trade-in": ["The trade-in details are confusing", "I don't understand the trade-in details when adding a trade-in"],
        "Accessibility Options do not work": ["The accessibility options on the website are not working", "I'm having trouble with the website's accessibility options"],
        "Contact Support / Us options are hard to find": ["I can't find the contact support options", "Where can I find the 'Contact Us' options?"],
        "My Orders Page Feedback": ["I have feedback about the 'My Orders' page", "I'm having issues with the 'My Orders' page"],
        "Website Pop Up - Feedback": ["I have feedback about the website pop-ups", "The website pop-ups are annoying"],
        "Website Search Feature - Poor Results": ["The website's search feature gives poor results", "I'm not satisfied with the search results on the website"],
        "Website Product Compare Tool Feedback": ["I have feedback about the product comparison tool", "The product comparison tool on the website could be improved"],
        "Outlet or Live Commerce Pop Up": ["The outlet pop-up on the website is intrusive", "I have feedback about the live commerce pop-up"],
        "Mobile Webpage and App Problem": ["I'm having problems with the mobile webpage", "The app is not working properly"],
        "Search Functionality Feedback": ["I have feedback about the search functionality", "The search functionality could be improved"],
        "Issues with finding the right product": ["I'm having trouble finding the right product on the website", "It's hard to find the product I want on the website"],
        "Slow and laggy Website performance": ["The website is slow and laggy", "I'm experiencing performance issues with the website"],
        "Slow and laggy Mobile App Performance": ["The mobile app is slow and laggy", "I'm experiencing performance issues with the mobile app"],
        "Stuck in Employee Store, Unable to Navigate Away": ["I'm stuck in the employee store and can't navigate away", "I can't get out of the employee store on the website"],
        "Navigation Issues for Samsung Business Store": ["I'm having navigation issues with the Samsung Business Store", "The Samsung Business Store is hard to navigate"],
        "The Website crashed frequently, making browsing and ordering a difficult process": ["The website keeps crashing, making it hard to browse and order", "I'm having trouble ordering because the website keeps crashing"],
        "Website Did not use my geo location accurately": ["The website did not use my geo-location accurately", "The website is not accurately detecting my location"]
    },
    "Product Support, Warranty and Repair (Care)": {
        "Loaner Phone Request for repair": ["I need a loaner phone for the repair", "Can I get a loaner phone while my phone is being repaired?"],
        "Product Registration issues - unable to register Samsung Product": ["I'm having issues registering my Samsung product", "I can't register my Samsung product"],
        "Cost of Repair is too high": ["The cost of repair is too high", "I can't afford the repair cost"],
        "Have to make Multiple Repair Requests": ["I have to make multiple repair requests", "Why do I need to request a repair multiple times?"],
        "Outside of Warranty Coverage - Unable to have device fixed": ["My device is outside of warranty coverage and can't be fixed", "I can't get my device fixed because it's out of warranty"],
        "Repair Lost in Transit": ["My repair got lost in transit", "The courier lost my device that was sent for repair"],
        "Care Plus + Subscription Coverage": ["I have a question about Care Plus+ subscription coverage", "Can you tell me more about Care Plus+ subscription coverage?"],
        "Need Help Troubleshooting Product": ["I need help troubleshooting my product", "Can you help me troubleshoot my product?"],
        "Troubleshooting steps did not work": ["The troubleshooting steps did not work", "I tried troubleshooting but it didn't help"],
        "Product Issues Were not Resolved by Care": ["Care did not resolve my product issues", "My product issues were not resolved by Care"],
        "Technical Product Support Did not Follow Up": ["Technical product support did not follow up", "I didn't get a follow-up from technical product support"],
        "Received Incorrect Troubleshooting from Product Tech Support": ["I received incorrect troubleshooting from product tech support", "The troubleshooting advice from tech support was wrong"],
        "Technical Product Support Hours Were Limited": ["The technical product support hours are too limited", "I need tech support but the hours are too limited"],
        "Repair Work Was Unsatisfactory": ["The repair work was unsatisfactory", "I'm not satisfied with the repair work"],
        "Repair Work Took Too Long": ["The repair work took too long", "I had to wait too long for the repair"]
    },
    "Return and Refund Issues": {
        "Return Refund Processing Time after return delivered": ["The return refund processing time is too long after the return was delivered", "How long does it take to process a refund after the return is delivered?"],
        "Return Window Extension Request to ship return later": ["I need an extension on the return window to ship the return later", "Can I get an extension on the return window?"],
        "Return Shipping Label Request, return already requested": ["I need a return shipping label, I've already requested a return", "Can I get a return shipping label?"],
        "Customer is frustrated that they need to wait for a return and refund before they can place a new order": ["I'm frustrated that I have to wait for a return and refund before I can place a new order", "Why do I have to wait for a return and refund to place a new order?"],
        "Shipping Label Print Requirement, need to print label": ["I need to print the shipping label for the return", "Can you send me a printable shipping label for the return?"],
        "General Return Policy - How to Return, restrictions?": ["Can you explain the return policy and how to return an item?", "What are the restrictions on returns?"],
        "Wrong Return Refund Amount received after Return": ["I received the wrong refund amount after returning an item", "The refund amount I received after the return is incorrect"],
        "My Return Failed and I did not receive a refund": ["My return failed and I didn't receive a refund", "I didn't get a refund because my return failed"],
        "My Return failed and it was Unsent": ["My return failed and it was unsent", "The return was not sent because it failed"],
        "My Installation Charge Was Deducted From Return Refund": ["My installation charge was deducted from the return refund", "Why was the installation charge deducted from my refund?"],
        "Had Difficulty Initiating a Return, no return option available": ["I had difficulty initiating a return, there's no return option available", "I can't initiate a return because there's no return option"],
        "I want a Refund for an order I placed": ["I want a refund for an order I placed", "Can I get a refund for my order?"],
        "I want an Exchange or Replacement": ["I want to exchange or replace my product", "Can I get a replacement or exchange my product?"],
        "Refund Was Not Issued After Return": ["I didn't receive a refund after returning the product", "The refund was not issued after I returned the product"],
        "Restocking Fees Deducted From Refund": ["Restocking fees were deducted from my refund", "Why were restocking fees deducted from my refund?"],
        "Needs to have order picked up for Return, unable to ship": ["I need the order to be picked up for return, I can't ship it", "Can you arrange a pick-up for my return? I can't ship it"],
        "Discrepancies in Partial Refunds": ["There are discrepancies in the partial refunds", "I have a question about the partial refunds"],
        "Had Difficulty Tracking shipped Returned Item": ["I had difficulty tracking the returned item", "I can't track the item I returned"],
        "Had Difficulties with International Return": ["I had difficulties with an international return", "International returns are difficult"],
        "Product Was Damaged During Return Shipping": ["The product was damaged during return shipping", "My returned product got damaged during shipping"],
        "Tax Exception - Tax Refund Needed": ["I need a tax refund due to a tax exception", "Can I get a tax refund due to a tax exception?"],
        "Had Problems with Return Label": ["I had problems with the return label", "The return label is not working"]
    },
    "Product Feedback": {
        "Charger Not Included with my order": ["The charger was not included with my order", "My order didn't come with a charger"],
        "Product Durability is poor": ["The product durability is poor", "I'm not satisfied with the product's durability"],
        "General Product Feedback": ["I have some general feedback about the product", "Here's my feedback about the product"],
        "Mobile Applications Feedback": ["I have feedback about the mobile applications", "Here's my feedback about the mobile apps"],
        "Feedback on Pre-Installed Apps": ["I have feedback about the pre-installed apps", "Here's my feedback about the pre-installed apps"],
        "There is still no headphone / speaker port on the newest phones.": ["There's still no headphone or speaker port on the newest phones", "Why don't the newest phones have a headphone or speaker port?"],
        "The product that I wanted was out of stock by the time I tried to order it.": ["The product I wanted was out of stock when I tried to order it", "I couldn't order the product I wanted because it was out of stock"],
        "Product Missing Piece or Part": ["The product is missing a piece or part", "There's a piece or part missing from the product"]
    },
    "Policy Feedback": {
        "Customer does not like the Trade-In Chargeback Process": ["I don't like the trade-in chargeback process", "The trade-in chargeback process is not satisfactory"],
        "Customer is frustrated at the Inability to Replace Items": ["I'm frustrated at the inability to replace items", "Why can't I replace items?"],
        "Concerns about Device Knox Locking and Disabling Policies": ["I have concerns about the device Knox locking and disabling policies", "Can you explain the device Knox locking and disabling policies?"],
        "Customer is providing Shipping Policy Critiques": ["I have some critiques about the shipping policy", "Here's my feedback about the shipping policy"],
        "Customer is providing Return Policy Critique": ["I have some critiques about the return policy", "Here's my feedback about the return policy"],
        "What are the Accepted Payment Methods?": ["What are the accepted payment methods?", "Can you tell me the accepted payment methods?"],
        "General questions about the Tax Exception Policy": ["I have some general questions about the tax exception policy", "Can you explain the tax exception policy?"]
    },
    "Post-Checkout Order Processing Issues": {
        "My Order was cancelled - Buy Online Pickup in store": ["My order was cancelled - I chose the buy online pickup in store option", "Why was my order cancelled? I chose to pick it up in store"],
        "My Order was cancelled - Financing": ["My order was cancelled - I chose the financing option", "Why was my order cancelled? I chose to finance it"],
        "My Order was cancelled - Fraud": ["My order was cancelled due to fraud", "Why was my order cancelled for fraud?"],
        "My Order was cancelled - Unknown reason": ["My order was cancelled for an unknown reason", "Why was my order cancelled? I don't understand the reason"],
        "My order was cancelled several times, I attempted to order again and again.": ["My order was cancelled several times, even though I tried to order again and again", "Why was my order cancelled multiple times? I kept trying to order"]
    },
    "Post-Checkout Order Modification and Management": {
        "Unable to Change Available Delivery Options": ["I'm unable to change the available delivery options", "I can't change the delivery options for my order"],
        "Unable to Cancel order": ["I'm unable to cancel my order", "I can't cancel my order"],
        "Unable to Modify Products on order": ["I'm unable to modify the products on my order", "I can't change the products on my order"],
        "Unable to Add Product to Order": ["I'm unable to add a product to my order", "I can't add a product to my order"],
        "Unable to Modify Payment Methods": ["I'm unable to modify the payment methods for my order", "I can't change the payment methods for my order"],
        "I had to cancel my order to make any changes, such as a different color.": ["I had to cancel my order to make changes, like choosing a different color", "Why do I have to cancel my order to make changes?"],
        "Customer wants to cancel an order they placed": ["I want to cancel an order I placed", "Can I cancel my order?"]
    },
    "Shipping and Delivery Issues, Where is my Order?": {
        "Where is my Order - Order has not shipped yet - Late": ["Where is my order? It hasn't shipped yet and it's late", "My order is late and it hasn't shipped yet"],
        "Customer wants to know about when an order will ship and be delivered": ["When will my order ship and be delivered?", "Can you tell me when my order will ship and be delivered?"],
        "Where is my Order - Order has shipped - Late": ["Where is my order? It has shipped but it's late", "My order is late even though it has shipped"],
        "Where is my Order - Order Lost in Transit, no Tracking Updates": ["Where is my order? It's lost in transit and there are no tracking updates", "My order is lost in transit and I can't track it"],
        "Where is my Order - Delivery Date Keeps Changing and Getting Pushed Out": ["Where is my order? The delivery date keeps changing and getting pushed out", "The delivery date for my order keeps getting pushed out"],
        "Original Delivery Date Was Changed Immediately After Placing Order": ["The original delivery date was changed immediately after I placed the order", "Why was the delivery date changed right after I placed the order?"],
        "Where is my Order - Product Missing from Shipment": ["Where is my order? There's a product missing from the shipment", "A product is missing from my order's shipment"],
        "Wrong Product Received - Color": ["I received the wrong product - the color is incorrect", "The product I received is the wrong color"],
        "Wrong Product Received - Model": ["I received the wrong product - the model is incorrect", "The product I received is the wrong model"],
        "Wrong Product Received - General": ["I received the wrong product", "The product I received is not what I ordered"],
        "BESPOKE Fridge / Refrigerator Panels - Not Shipped Delay": ["The BESPOKE fridge/refrigerator panels have not been shipped yet", "Why haven't the BESPOKE fridge/refrigerator panels been shipped yet?"],
        "Customization and Exclusive Color delivery delay Time, weeks": ["The delivery of the customization and exclusive color is delayed by weeks", "Why is the delivery of the customization and exclusive color delayed?"],
        "Buy Online Pickup in store - Best Buy Pickup Delay": ["The pickup at Best Buy is delayed", "Why is the pickup at Best Buy delayed?"],
        "Buy Online Pickup in store - Best Buy Out of stock Delay": ["The pickup at Best Buy is delayed because the product is out of stock", "Why is the pickup at Best Buy delayed? The product is out of stock"],
        "Buy Online Pickup in store - Best Buy No Pick Up Ready Confirmation": ["I didn't receive a pick-up ready confirmation from Best Buy", "Why haven't I received a pick-up ready confirmation from Best Buy?"],
        "Where is my order - Order Delivered, but not Received": ["Where is my order? It was delivered but I didn't receive it", "My order was delivered but I didn't receive it"],
        "Defective Product delivered and Received, DOA, unit does not work": ["I received a defective product, it doesn't work", "The product I received is defective and doesn't work"],
        "No Tracking Information - UPS": ["I don't have any tracking information from UPS", "Why haven't I received any tracking information from UPS?"],
        "No Tracking Information - AGS": ["I don't have any tracking information from AGS", "Why haven't I received any tracking information from AGS?"],
        "No Tracking Information - Buy Online Pickup in store": ["I don't have any tracking information for my buy online pickup in store order", "Why haven't I received any tracking information for my buy online pickup in store order?"],
        "No Tracking Information - FedEx": ["I don't have any tracking information from FedEx", "Why haven't I received any tracking information from FedEx?"],
        "No Tracking Information - Forward Air": ["I don't have any tracking information from Forward Air", "Why haven't I received any tracking information from Forward Air?"],
        "No Tracking Information - RXO": ["I don't have any tracking information from RXO", "Why haven't I received any tracking information from RXO?"],
        "No Tracking Information - Unknown": ["I don't have any tracking information", "Why haven't I received any tracking information?"],
        "Received Damaged Product, scratched, dented, etc": ["I received a damaged product, it's scratched and dented", "The product I received is damaged, it has scratches and dents"],
        "Where is my Order - Delivery Date was Missed": ["Where is my order? The delivery date was missed", "The delivery date for my order was missed"],
        "Where is my Order - Inaccurate Delivery Tracking": ["Where is my order? The delivery tracking is inaccurate", "The delivery tracking for my order is inaccurate"],
        "Unable to checkout - Limited Delivery Zones, shipping restriction": ["I'm unable to checkout due to limited delivery zones and shipping restrictions", "Why can't I checkout? There are shipping restrictions and limited delivery zones"],
        "Where is my Order - Delivered to Wrong Location or Address": ["Where is my order? It was delivered to the wrong location or address", "My order was delivered to the wrong location or address"],
        "Where is my Order - Delivery Attempted, but not completed": ["Where is my order? The delivery was attempted but not completed", "The delivery for my order was attempted but not completed"]
    },
    "Customer Service and Contact Feedback": {
        "Customer Service Agent Unable to Solve Issue": ["The customer service representative couldn't resolve my issue", "I'm unsatisfied with the problem-solving ability of the customer service agent"],
        "Service Level Expectation, why did it take so long to connect?": ["Why was the waiting time to connect with customer service so long?", "I had to wait too long to reach customer service"],
        "Customer Service Agent Knowledge is lacking": ["The customer service agent seemed uninformed", "The representative didn't have enough knowledge to help me"],
        "Customer Service Agent Ownership and follow up is poor": ["The customer service representative failed to follow up", "The customer service agent did not take responsibility for my issue"],
        "Technical Issues - too much Time to Resolve": ["It took too long to fix my technical issues", "The resolution of my technical problem was delayed"],
        "Contact Disconnected, no callback or e-mail received": ["My call was disconnected and I received no callback or email", "I was disconnected and received no follow-up"],
        "Long Wait Times for Agent Support Response": ["I had to wait a long time for a response from the agent", "The agent's response time was too long"],
        "Put on Hold for Far Too Long during conversation": ["I was kept on hold for too long during the call", "The hold time during the conversation was too long"],
        "Language Barrier with Customer Support Staff, Difficult to Understand": ["I had difficulty understanding the customer support due to a language barrier", "The customer service agent's accent made communication difficult"],
        "Too Much Time Between Chat Replies": ["The chat responses were too slow", "It took too long to get responses in the chat"],
        "Lack of Empathy from Customer Support Staff": ["The customer service agent lacked empathy", "I didn't feel understood by the customer service representative"],
        "Supervisor was Not Helpful during call or chat": ["The supervisor on the call was not helpful", "I didn't find the chat supervisor helpful"],
        "Agent Would Not Escalate or Let Me Talk / chat with Supervisor": ["The agent refused to escalate my issue", "I wasn't allowed to speak with a supervisor"],
        "Customer is stating they will go to a competitor, Apple, as a result of poor treatment.": ["I'm considering switching to Apple due to poor service", "Due to this bad experience, I'm thinking of going to a competitor like Apple"],
        "Customer service Agent is repeating the same troubleshooting or advice and it continues to not be effective.": ["The agent keeps repeating the same ineffective troubleshooting steps", "The agent's advice is not solving the issue, yet they keep repeating it"],
        "Customer service is closed, unable to call or chat, no one is available to help me.": ["I can't reach customer service, it's closed", "I can't call or chat with anyone, customer service seems to be closed"],
        "At This Point, Immediate Supervisor or Leader is Required": ["I need to speak with a supervisor right now", "It's important for me to talk to a leader immediately"]
    },
        "Checkout and Cart Issues": {
            "Unable to checkout - Payment Issue": ["Unable to process payment during checkout", "Payment processing issue"],
            "Long Delivery Time": ["Delivery time is too long", "Expected delivery time deters purchase"],
            "Carrier Website Issues": ["Unable to log into Verizon's site to finish checkout", "Unable to log into T-Mobile's website for checkout", "Login issues on AT&T are preventing checkout"],
            "Price Issue": ["Price changes during checkout", "Discrepancy between product page price and cart price"],
            "Checkout Error Messages": ["Error message prevents checkout", "Unable to checkout due to error message"],
            "Finance Offer Changes": ["Finance offer changes during checkout", "Alterations in finance offer in the cart and at checkout"],
            "Promotion EPP Issue - Discount": ["Employee Purchase Program discount issue", "Student or Teacher discount isn't working", "First Responder or Military discount problem"],
            "Payment Issue": ["Samsung Financing issues prevent checkout", "Carrier Financing problems stopping me from ordering", "Credit Card issue, unable to place order", "Apple Pay, PayPal not working", "Affirm Financing isn't working for payments", "Klarna Financing is not available for my purchase", "Unknown payment method type", "Available financing credit isn't working"],
            "Promotion Issue": ["Promotion isn't being applied", "Invalid promo code"],
            "Reward Points Issue": ["Reward points not applied to my order", "Unable to use reward points"],
            "Split Payment Issue": ["Split payment option isn't working", "Issues with multiple payment options"],
            "Technical Issue During Checkout": ["Unable to checkout due to technical issue", "Technical problems prevent checkout"],
            "$50 Reserve Reservation Promo Credit Issue": ["$50 Reserve Reservation promo credit not applying", "Invalid or unapplied $50 Reserve  promo credit"],
            "Shipping Issues": ["Limited shipping methods and speeds", "Unable to verify shipping address error message at checkout"],
            "Order Cancelled Repeatedly": ["Order cancelled repeatedly, regardless of payment method", "Payment method charged despite order being cancelled", "Order cancelled shortly after multiple attempts to place it", "Repeated order cancellation notifications from Samsung"],
            "Cart Issue": ["All products removed from cart", "Unable to modify quantity of order"]
        },

    "Installation Problems": {
        "Complex Installation Process": ["The installation process is complex and requires multiple visits by the installers"],
        "Missed Installation Appointment": ["The installers missed my installation appointment"],
        "Late Arrival of Installers": ["The installers arrived late for the appointment"],
        "Missing Installation Parts": ["There are missing parts, so I can't install the products"],
        "Damages Caused by Installers": ["The installers damaged my home appliance", "My home or property was damaged during the installation", "The installers damaged my TV"],
        "Rude Installation Staff": ["The installation staff were rude during the service"],
        "Post-Installation Product Issues": ["There are issues with the product after it was installed"],
        "Installation Not Done At Delivery": ["The product was not installed at the time of delivery"]
    },
    "Privacy & Security Concerns": {
        "Website Data Security and Privacy": ["I have concerns about the security and privacy of my data on the website"],
        "Lack of Transparency in Data Usage": ["There's a lack of transparency in how my data is being used"],
        "Scams & Phishing Experiences": ["I've experienced scams and phishing"],
        "Payment Information Security": ["I'm concerned about the security of my payment information"],
        "Privacy Settings Issues": ["I'm having issues with the privacy settings"]
    },
    "Account Management Issues": {
        "Login Issues": ["I'm unable to log into my account", "I can't log into my Samsung account on my mobile device"],
        "Password Retrieval": ["I can't retrieve my lost password"],
        "Verification Email": ["I didn't receive the account verification email"],
        "Account Information Modification": ["I'm unable to change my account information"],
        "Account Creation": ["I experienced an issue during account creation"],
        "Account Deactivation or Deletion": ["I'm unable to deactivate or delete my account"],
        "Account Suspension or Ban": ["My account was suspended or banned unexpectedly"],
        "Linking Multiple Accounts": ["I had difficulty linking multiple accounts"],
        "Two-factor Authentication": ["I'm unable to pass two-factor authentication, preventing log in to the site"],
        "Unwanted Marketing Communications": ["I received unwanted marketing emails and text messages"],
        "Preference Settings": ["I'm unable to set preferences in my account"]
    },
    "Pre-Order Product Questions": {
        "Product Details Needed": ["I need details for Samsung mobile phones", "I need information about the newest Samsung Galaxy phone", "I need details about Samsung Galaxy Watch models", "I need information about Samsung home appliances", "I need details about Samsung consumer electronics", "I need information about Samsung televisions"],
        "Product Comparisons": ["I need comparisons for Samsung mobile products"],
        "Product Availability": ["When will this product be available again?", "I'm an international customer and need to know about product availability"],
        "Product Compatibility": ["I have questions about product compatibility"]
    },
    "Accessibility Feedback": {
        "Samsung Mobile Phones": ["I have feedback about accessibility options for Samsung mobile phones"],
        "Samsung Mobile Devices": ["I have feedback about accessibility options for other Samsung mobile devices"],
        "Samsung Tablets": ["I have feedback about accessibility options for Samsung tablets"],
        "Samsung Wearable Devices": ["I have feedback about accessibility options for Samsung wearable devices"],
        "Samsung Home Appliances": ["I have feedback about accessibility options for Samsung home appliances"],
        "Samsung Televisions": ["I have feedback about accessibility options for Samsung televisions"],
        "Samsung Consumer Electronics": ["I have feedback about accessibility options for Samsung consumer electronics"],
        "Samsung Computers and Laptops": ["I have feedback about accessibility options for Samsung computers and laptops"],
        "Samsung Monitors": ["I have feedback about accessibility options for Samsung monitors"]
    }
}

