default_categories = {

   "Website Design & Navigation": {
       "Issue1": [""],
    },
   "Product Information": {
       "Issue1": [""],
    },
   "Online Purchasing": {
       "Issue1": [""],
    },
   "Delivery & Installation": {
       "(DA) Cancelled" : [""],
       "(DA) Carrier Feedback" : [""],
       "(DA) Damages" : [""],
       "(DA) Empty Box" : [""],
       "(DA) Incorrect Delivery Dates - Post" : [""],
       "(DA) Installation Issues" : [""],
       "(DA) Lack of Delivery Delay Notification" : [""],
       "(DA) Lack of Delivery Service" : [""],
       "(DA) Lack of Delivery Service AGS" : [""],
       "(DA) Lack of Delivery Service FedEx" : [""],
       "(DA) Lack of Delivery Service Forward Air" : [""],
       "(DA) Lack of Delivery Service RXO" : [""],
       "(DA) Lack of Delivery Service UPS" : [""],
       "(DA) No Delivery" : [""],
       "(DA) Reschedules - No Cx notification" : [""],
       "(DA) Tracking Issues" : [""],
       "(DA) Where's My Stuff - Not Agent Related (Not BOPIS)" : [""],
       "(DA) Wrong Address" : [""],
       "(DA) Wrong Product Received" : [""],
       "(VD) Cancelled" : [""],
       "(VD) Carrier Feedback" : [""],
       "(VD) Damages" : [""],
       "(VD) Empty Box" : [""],
       "(VD) Incorrect Delivery Dates - Post" : [""],
       "(VD) Installation Issues" : [""],
       "(VD) Lack of Delivery Delay Notification" : [""],
       "(VD) Lack of Delivery Service" : [""],
       "(VD) Lack of Delivery Service AGS" : [""],
       "(VD) Lack of Delivery Service FedEx" : [""],
       "(VD) Lack of Delivery Service Forward Air" : [""],
       "(VD) Lack of Delivery Service RXO" : [""],
       "(VD) Lack of Delivery Service UPS" : [""],
       "(VD) No Delivery" : [""],
       "(VD) Reschedules - No CX notification" : [""],
       "(VD) Tracking Issues" : [""],
       "(VD) Where's My Stuff - Not Agent Related (Not BOPIS)" : [""],
       "(VD) Wrong Address" : [""],
       "(VD) Wrong Product Received" : [""],
       "(MX) Cancelled" : [""],
       "(MX) Carrier Feedback" : [""],
       "(MX) Damages" : [""],
       "(MX) Empty Box" : [""],
       "(MX) Incorrect Delivery Dates - Post" : [""],
       "(MX) Lack of Delivery Delay Notification" : [""],
       "(MX) Lack of Delivery Service" : [""],
       "(MX) Lack of Delivery Service AGS" : [""],
       "(MX) Lack of Delivery Service FedEx" : [""],
       "(MX) Lack of Delivery Service Forward Air" : [""],
       "(MX) Lack of Delivery Service RXO" : [""],
       "(MX) Lack of Delivery Service UPS" : [""],
       "(MX) No Delivery" : [""],
       "(MX) Tracking Issues" : [""],
       "(MX) Where's My Stuff - Not Agent Related (Not BOPIS)" : [""],
       "(MX) Wrong Address" : [""],
       "(MX) Wrong Product Received" : [""],
    },
   "eCom Support": {
       "Issue1": [""],
    },
   "CARE Support": {
       "Issue1": [""],
    },
}
