default_categories = {
    "Website Content / App Critical Feedback": [
        "Help Pages and FAQs are hard to find",
        "Missing Product Details on Website",
        "Promotion Details are not clear",
        "Trade in Details are not clear when adding trade-in",
        "Accessibility Options do not work",
        "Contact Support / Us options are hard to find",
        "My Orders Page Feedback",
        "Website Pop Up - Feedback",
        "Website Search Feature - Poor Results",
        "Website Product Compare Tool Feedback",
         "Outlet or Live Commerce Pop Up",
         "Mobile Webpage and App Problem",
        "Search Functionality Feedback",
        "Issues with finding the right product",
        "Slow and laggy Website performance",
        "Slow and laggy Mobile App Performance",
        "Stuck in Employee Store, Unable to Navigate Away",
        "Navigation Issues for Samsung Business Store",
        "The Website crashed frequently, making browsing and ordering a difficult process",
        "Website Did not use my geo location accurately"
    ],
    "Product Support, Warranty and Repair (Care)": [
        "Loaner Phone Request for repair",
        "Product Registration issues - unable to register Samsung Product",
        "Cost of Repair is too high",
        "Have to make Multiple Repair Requests",
        "Outside of Warranty Coverage - Unable to have device fixed",
        "Repair Lost in Transit",
        "Care Plus + Subscription Coverage",
        "Need Help Troubleshooting Product",
        "Troubleshooting steps did not work",
        "Product Issues Were not Resolved by Care",
        "Technical Product Support Did not Follow Up",
        "Received Incorrect Troubleshooting from Product Tech Support",
        "Technical Product Support Hours Were Limited",
        "Repair Work Was Unsatisfactory",
        "Repair Work Took Too Long"
    ],
    "Return and Refund Issues": [
        "Return Refund Processing Time after return delivered",
        "Return Window Extension Request to ship return later",
        "Return Shipping Label Request, return already requested",
        "Customer is frustrated that they need to wait for a return and refund before they can place a new order",
        "Shipping Label Print Requirement, need to print label",
        "General Return Policy - How to Return, restrictions?",
        "Wrong Return Refund Amount received after Return",
        "My Return Failed and I did not receive a refund",
        "My Return failed and it was Unsent",
        "My Installation Charge Was Deducted From Return Refund",
        "Had Difficulty Initiating a Return, no return option available",
        "I want a Refund for an order I placed",
        "I want an Exchange or Replacement",
        "Refund Was Not Issued After Return",
        "Restocking Fees Deducted From Refund",
        "Needs to have order picked up for Return, unable to ship",
        "Discrepancies in Partial Refunds",
        "Had Difficulty Tracking shipped Returned Item",
        "Had Difficulties with International Return",
        "Product Was Damaged During Return Shipping",
        "Tax Exception - Tax Refund Needed",
        "Had Problems with Return Label"
    ],
    "Product Feedback": [
        "Charger Not Included with my order",
        "Product Durability is poor",
        "General Product Feedback",
        "Mobile Applications Feedback",
        "Feedback on Pre-Installed Apps",
        "There is still no headphone / speaker port on the newest phones.",
        "The product that I wanted was out of stock by the time I tried to order it.",
        "Product Missing Piece or Part"
    ],
    "Policy Feedback": [
        "Customer does not like the Trade-In Chargeback Process",
        "Customer is frustrated at the Inability to Replace Items",
        "Concerns about Device Knox Locking and Disabling Policies",
        "Customer is providing Shipping Policy Critiques",
        "Customer is providing Return Policy Critique",
        "What are the Accepted Payment Methods?",
        "General questions about the Tax Exception Policy"
    ],
    "Post-Checkout Order Processing Issues": [
        "My Order was cancelled - Buy Online Pickup in store",
        "My Order was cancelled - Financing",
        "My Order was cancelled - Fraud",
        "My Order was cancelled - Unknown reason",
        "My order was cancelled several times, I attempted to order again and again."
    ],
    "Post-Checkout Order Modification and Management": [
        "Unable to Change Available Delivery Options",
        "Unable to Cancel order",
        "Unable to Modify Products on order",
        "Unable to Add Product to Order",
        "Unable to Modify Payment Methods",
        "I had to cancel my order to make any changes, such as a different color.",
        "Customer wants to cancel an order they placed"
    ],
    "Shipping and Delivery Issues, Where is my Order?": [
        "Where is my Order - Order has not shipped yet - Late",
        "Customer wants to know about when an order will ship and be delivered",
        "Where is my Order - Order has shipped - Late",
        "Where is my Order - Order Lost in Transit, no Tracking Updates",
        "Where is my Order - Delivery Date Keeps Changing and Getting Pushed Out",
        "Original Delivery Date Was Changed Immediately After Placing Order"
        "Where is my Order - Product Missing from Shipment",
        "Wrong Product Received - Color",
        "Wrong Product Received - Model",
        "Wrong Product Received - General",
        "BESPOKE Fridge / Refrigerator Panels - Not Shipped Delay",
        "Customization and Exclusive Color delivery delay Time, weeks",
        "Buy Online Pickup in store - Best Buy Pickup Delay",
        "Buy Online Pickup in store - Best Buy Out of stock Delay",
        "Buy Online Pickup in store - Best Buy No Pick Up Ready Confirmation",
        "Where is my order - Order Delivered, but not Received",
        "Defective Product delivered and Received, DOA, unit does not work",
        "No Tracking Information - UPS",
        "No Tracking Information - AGS",
        "No Tracking Information - Buy Online Pickup in store",
        "No Tracking Information - FedEx",
        "No Tracking Information - Forward Air",
        "No Tracking Information - RXO",
        "No Tracking Information - Unknown",
        "Received Damaged Product, scratched, dented, etc",
        "Where is my Order - Delivery Date was Missed",
        "Where is my Order - Inaccurate Delivery Tracking",
        "Unable to checkout - Limited Delivery Zones, shipping restriction",
        "Where is my Order - Delivered to Wrong Location or Address",
        "Where is my Order - Delivery Attempted, but not completed"
    ],
    "Customer Service and Contact Feedback": [
        "Customer Service Agent Unable to Solve Issue",
        "Service Level Expectation, why did it take so long to connect?",
        "Customer Service Agent Knowledge is lacking",
        "Customer Service Agent Ownership and follow up is poor",
        "Technical Issues - too much Time to Resolve",
        "Contact Disconnected, no callback or e-mail received",
        "Long Wait Times for Agent Support Response",
        "Put on Hold for Far Too Long during conversation",
        "Language Barrier with Customer Support Staff, Difficult to Understand",
        "Too Much Time Between Chat Replies",
        "Lack of Empathy from Customer Support Staff",
        "Supervisor was Not Helpful during call or chat",
        "Agent Would Not Escalate or Let Me Talk / chat with Supervisor",
        "Customer is stating they will go to a competitor, Apple, as a result of poor treatment.",
        "Customer service Agent is repeating the same troubleshooting or advice and it continues to not be effective.",
        "Customer service is closed, unable to call or chat, no one is available to help me.",
        "At This Point, Immediate Supervisor or Leader is Required"
    ],
    "Checkout and Cart Issues": [
        "Unable to checkout - Payment Issue",
        "Customer does not want to order because delivery will take too long",
        "Verizon, unable to log into Carrier Website to complete checkout",
        "T-Mobile, unable to log into Carrier Website to complete checkout",
        "ATT / AT&T, unable to log into Carrier Website to complete checkout",
        "Price Changing in Cart and Checkout when I try to order",
        "Price in cart is higher than the product page, click to order one price and higher price is given when ordering",
        "Error Message Preventing Checkout",
        "Finance Offer Changes in Cart and Checkout",
        "Promotion EPP Issue - Employee Purchase Program Discount",
        "Promotion EPP Issue - Student or Teacher Discount",
        "Promotion EPP Issue - First Responder or Military Discount",
        "Payment Issue - Samsung Financing Customer unable to checkout",
        "Payment Issue - Carrier Financing preventing placing order",
        "Payment Issue - Credit Card unable to place order",
        "Payment Issue - Apple Pay, PayPal is not working",
        "Payment Issue - Affirm Financing is not working",
        "Payment Issue - Klarno Financing is not available",
        "Payment Issue - Unknown Payment method type",
        "Payment Issue - Financing Credit Available, but Not Working",
        "Promotion Issue - Promotion Not Applied or promo is invalid",
        "Reward Points are Not Applied to my order.",
        "Split Payment Not Working, want multiple payment options",
        "Unable to checkout - Technical Issue",
        "$50 dollar Reserve Reservation promo Credit - Not Applying or invalid",
        "$50 dollar Reserve Reservation Reserve Credit - Not Received",
        "Limited Shipping Methods and speeds",
        "Unable to Verify Shipping Address error message receieved at checkout",
        "Customer is able to place their order, but it is cancelled repeatedly, regardless of payment method.",
        "My payment method was charged, despite the order being cancelled or not placed at all.",
        "When I place an order, or attempt ordering multiple times, the order is cancelled shorlty after.",
        "All items/products are removed from cart, difficult to make changes to order prior to it being placed.",
        "Samsung Order Cancelled Notification Sent Repeatedly after I make an order.",
        "Unable to Modify Quantity of the order I want to place"
        ],
    "Installation Problems": [
        "Complex Installation Process, multiple visits by installers required",
        "Installation Appointment was missed by installers",
        "Installers Arrived Late for the appointment",
        "Missing Installation Parts, so unable to install products",
        "Installers Damaged my Home Appliance product",
        "Installers Damaged my Home or Property",
        "Installers Damaged my TV / Television product",
        "Rude Installation Staff at the time of service",
        "Issues with product after it was installed",
        "Installation Did Not Happen At Delivery"
    ],
    "Privacy & Security Concerns": [
        "Concerns about Website Data Security and Privacy",
        "Lack of Transparency in Data Usage",
        "Experiences of Scams & Phishing",
        "Payment Information Security Concerns",
        "Issues with Privacy Settings"
    ],
    "Account Management Questions and Issues": [
        "Unable to Log into my Account",
        "Could Not Retrieve Lost Password",
        "Did not Receive Account Verification Email",
        "Unable to Change Account Information",
        "Experienced Issue During Account Creation",
        "Unable to Deactivate or Delete Account",
        "Account Was Suspended or Banned Unexpectedly",
        "Had Difficulty Linking Multiple Accounts",
        "Unable to pass two-factor (2 factor) authentification, preventing log in to site.",
        "Unable to log into my Samsung account on my mobile cell device.",
        "Received Unwanted Marketing Emails and Text Messages",
        "Unable to Set Preferences in Account"
    ],
    "Product Questions Before Placing Order": [
        "Product Details Needed - Samsung Mobile Phones",
        "Product Details Needed - the Newest Samsung Galaxy Phone Flagship",
        "Product Details Needed - Samsung Galaxy Watch 3, 4, 5, 40MM, 42MM, 44MM, 45MM",
        "Product Details Needed - Samsung Home Appliances",
        "Product Details Needed - Samsung Consumer Electronics",
        "Product Details Needed - Samsung Televisions (TVs)",
        "Product Comparisons for Mobile Products Needed",
        "When will this Product be Available Again?",
        "Need Help Choosing The Right Product",
        "Need Help Choosing The Right Galaxy Mobile device or Cell Phone",
        "Need Help Choosing The Right Galaxy Tablet",
        "Need Help Choosing The Right Ear buds",
        "Need Help Choosing The Right Home Appliance",
        "Need Help Choosing The Right Water Filter",
        "Need Help Choosing The Right Refrigerator or fridge",
        "Need Help Choosing The Right Stove or oven, range",
        "Need Help Choosing The Right Microwave",
        "Need Help Choosing The Right Clothes washer and dryer",
        "Need Help Choosing The Right Television or TV",
        "Need Help Choosing The Right Computer Monitor",
        "Need Help Choosing The Right Laptop",
        "What is the brightness maximum, or Nits max, of the screen on a phone or Tablet?",
        "What is the brightness maximum, or Nits max, of the screen on a Television, TV, or Monitor?",
        "Need Help Choosing The Right Galaxy Notebook"
    ],
    "Discount and Promotion Questions Before Placing Order": [
        "Best Discount and Promo for Samsung Galaxy Mobile Cell Phone?",
        "Best Discount and Promo for Samsung Television or TV?",
        "Best Discount and Promo for Samsung Home Appliances?",
        "Best Discount and Promo for Samsung Refrigerator or fridge?",
        "Best Discount and Promo for Samsung Stove or oven, range?",
        "Best Discount and Promo for Samsung Microwave?",
        "Best Discount and Promo for Samsung Clothes washer and dryer?",
        "How do I Apply Rewards Points to my order before it is placed?",
        "Discounts for Buying in Bulk?",
        "Applying Add-On Credit to my Order, want to make sure I get more off the price",
        "Additional Discounts for accessories",
        "Details Needed for Memory Upgrade when ordering a 256GB, 512GB, or 1TB Mobile Phone"
    ],
    "Post-Order Promotion and Subscription Questions": [
        "How do I redeem - YouTube Premium",
        "How do I redeem - Spotify",
        "How do I redeem - Art Store",
        "How do I redeem - Adobe Light Room",
        "How do I redeem - Microsoft OneDrive",
        "How do I redeem - Sirius XM Radio",
        "$100, $150, $200 ECertificate Redemption - When is it sent?",
        "$100, $150, $200 ECertificate Redemption - How to use?",
        "$100, $150, $200 ECertificate Redemption - Must Use it Now?"
    ],
    "Trade-In Program Questions and Issues": [
        "What is Cracked Screen Trade-in Offer?",
        "The full trade-in value of my device was not applied to the order.",
        "How to Check if Device Qualifies for trade-in?",
        "How much is This Device Worth as a trade-in?",
        "Trade-In Values Change in Cart / Checkout",
        "Trade-In Bill Credits are Different than instant credit",
        "Trade-In Failed and I was Charged for my trade-in",
        "Possible to Trade-in Multiple Devices when buying one product",
        "Trade-in Credit What if the order is Returned?",
        "Positive Trade-in Program feedback, customer wants and likes to trade in products.",
        "I am Disputing Trade-in Results"
    ],
}